logFilters:
  - level: discard
    pattern: '*@npm:* The darwin-* architecture'

nodeLinker: node-modules

npmScopes:
  saas-ui:
    npmRegistryServer: 'https://npm.saas-ui.dev'
npmRegistries:
  //npm.saas-ui.dev:
    npmAuthIdent: '${SAAS_UI_TOKEN:-}'
    npmAlwaysAuth: true

packageExtensions:
  '@chakra-ui/anatomy@*':
    dependencies:
      '@chakra-ui/system': '*'
      react: '*'
  '@chakra-ui/checkbox@*':
    dependencies:
      framer-motion: '*'
      react-dom: '*'
  '@chakra-ui/props-docs@*':
    dependencies:
      '@emotion/react': '*'
      '@emotion/styled': '*'
      framer-motion: '*'
      react: '*'
      react-dom: '*'
      typescript: '*'
  '@chakra-ui/skeleton@*':
    dependencies:
      '@chakra-ui/theme': '*'
  '@chakra-ui/transition@*':
    dependencies:
      framer-motion: '*'
      react-dom: '*'

plugins:
  - path: .yarn/plugins/@yarnpkg/plugin-workspace-tools.cjs
    spec: '@yarnpkg/plugin-workspace-tools'
  - path: .yarn/plugins/@yarnpkg/plugin-interactive-tools.cjs
    spec: '@yarnpkg/plugin-interactive-tools'

yarnPath: .yarn/releases/yarn-3.1.1.cjs
