packages:
  - apps/*
  - packages/storybook
  - packages/pro/packages/*
  - packages/saas-ui-*
  - tooling/next-workspaces
  - tooling/test-utils
  - tooling/props-docs
  - tooling/storybook-addon
onlyBuiltDependencies:
  - '@parcel/watcher'
