packages:
  - apps/website
  - apps/palette
  - apps/compositions
  - packages/storybook
  - packages/pro/packages/*
  - packages/saas-ui-*
  - tooling/next-workspaces
  - tooling/test-utils
  - tooling/props-docs
  - tooling/storybook-addon
  - examples/*
onlyBuiltDependencies:
  - '@parcel/watcher'

overrides:
  '@ark-ui/react': '5.20.0'
  '@chakra-ui/react': '3.25.0'
  'react': '19.1.1'
  'react-dom': '19.1.1'
  '@types/react': '19.1.10'
  '@types/react-dom': '19.1.7'
  'typescript': '5.8.3'
# hoistPattern:
#   - '@chakra-ui/react'
#   - '@ark-ui/react'
#   - 'zod'
