packages:
  - apps/website
  - apps/compositions
  - packages/storybook
  - packages/pro/packages/*
  - packages/saas-ui-*
  - tooling/next-workspaces
  - tooling/test-utils
  - tooling/props-docs
  - tooling/storybook-addon
  - examples/*
onlyBuiltDependencies:
  - '@parcel/watcher'
overrides:
  '@ark-ui/react': '5.20.0'
  '@chakra-ui/react': '3.25.0'
  'react': '19.0.0'
  '@types/react': '19.0.12'
hoistPattern:
  - '@chakra-ui/react'
  - '@ark-ui/react'
  - 'zod'
