packages:
  - 'apps/website'
  - 'apps/compositions'
  - 'packages/storybook'
  - 'packages/pro/packages/*'
  - 'packages/saas-ui-*'
  - 'tooling/next-workspaces'
  - 'tooling/test-utils'
  - 'tooling/props-docs'
  - 'tooling/storybook-addon'
