packages:
  - apps/website
  - apps/compositions
  - packages/storybook
  - packages/pro/packages/*
  - packages/saas-ui-*
  - tooling/next-workspaces
  - tooling/test-utils
  - tooling/props-docs
  - tooling/storybook-addon
  - examples/*
onlyBuiltDependencies:
  - '@parcel/watcher'
overrides:
  '@chakra-ui/react': '^3.30.0'
  '@ark-ui/react': '^5.30.0'
  '@saas-ui/forms': '3.0.0-next.51'
