packages:
  - apps/website
  - apps/compositions
  - packages/storybook
  - packages/pro/packages/*
  - packages/saas-ui-*
  - tooling/next-workspaces
  - tooling/test-utils
  - tooling/props-docs
  - tooling/storybook-addon
  - examples/*
onlyBuiltDependencies:
  - '@parcel/watcher'
overrides:
  '@zag-js/core': '1.17.4'
  '@ark-ui/react': '5.15.4'
  '@chakra-ui/react': '3.21.0'
  'react': '19.0.0'
  '@types/react': '19.0.12'
