export interface Parent {
  fileName: string
  name: string
}

export interface Declaration {
  fileName: string
  name: string
}

export interface DefaultProps {
  defaultValue?: any
  description: string | JSX.Element
  name: string
  parent: Parent
  declarations: Declaration[]
  required: boolean
  type: { name: string }
}

export interface PropDoc {
  tags: { see: string }
  filePath: string
  description: string | JSX.Element
  displayName: string
  methods: any[]
  props: {
    defaultProps?: DefaultProps
    components?: DefaultProps
  }
}

export declare const App: PropDoc
export declare const document: PropDoc
export declare const RelativeTime: PropDoc
export declare const DateTime: PropDoc
export declare const RelativeTime1: PropDoc
export declare const DateTime1: PropDoc
export declare const createPage: PropDoc
export declare const createPage1: PropDoc
export declare const BillingProvider: PropDoc
export declare const BillingProvider1: PropDoc
export declare const Sparklines: PropDoc
export declare const LineChart: PropDoc
export declare const LineChart1: PropDoc
export declare const Sparklines1: PropDoc
export declare const ActionButton: PropDoc
export declare const Day: PropDoc
export declare const ActionButton1: PropDoc
export declare const Day1: PropDoc
export declare const Input: PropDoc
export declare const Month: PropDoc
export declare const Input1: PropDoc
export declare const Month1: PropDoc
export declare const DateInput: PropDoc
export declare const DatePickerModal: PropDoc
export declare const DatePickerProvider: PropDoc
export declare const DatePickerContainer: PropDoc
export declare const DatePicker: PropDoc
export declare const DatePickerDialog: PropDoc
export declare const DatePickerStatic: PropDoc
export declare const DateRangeInput: PropDoc
export declare const DatePickerProvider1: PropDoc
export declare const DatePickerContainer1: PropDoc
export declare const DatePicker1: PropDoc
export declare const DatePickerDialog1: PropDoc
export declare const DatePickerStatic1: PropDoc
export declare const DatePickerModal1: PropDoc
export declare const DateRangeInput1: PropDoc
export declare const DateInput1: PropDoc
export declare const useDatePickerModal: PropDoc
export declare const useDatePicker: PropDoc
export declare const useYear: PropDoc
export declare const Has: PropDoc
export declare const Has1: PropDoc
export declare const FeaturesProvider: PropDoc
export declare const FeaturesProvider1: PropDoc
export declare const BenefitsModal: PropDoc
export declare const BenefitsModalContainer: PropDoc
export declare const BenefitsModalMedia: PropDoc
export declare const BenefitsModalActions: PropDoc
export declare const BenefitsModal1: PropDoc
export declare const BenefitsModalContainer1: PropDoc
export declare const BenefitsModalMedia1: PropDoc
export declare const BenefitsModalActions1: PropDoc
export declare const TourDialog: PropDoc
export declare const TourDialogContainer: PropDoc
export declare const TourDialogActions: PropDoc
export declare const TourDialogPrimaryAction: PropDoc
export declare const TourDialogSecondaryAction: PropDoc
export declare const Tour: PropDoc
export declare const TourNextButton: PropDoc
export declare const TourPrevButton: PropDoc
export declare const TourDismissButton: PropDoc
export declare const MotionBox: PropDoc
export declare const TourSpotlight: PropDoc
export declare const TourBeacon: PropDoc
export declare const TourDialog1: PropDoc
export declare const TourDialogContainer1: PropDoc
export declare const TourDialogActions1: PropDoc
export declare const TourDialogPrimaryAction1: PropDoc
export declare const TourDialogSecondaryAction1: PropDoc
export declare const MotionBox1: PropDoc
export declare const TourSpotlight1: PropDoc
export declare const Tour1: PropDoc
export declare const TourNextButton1: PropDoc
export declare const TourPrevButton1: PropDoc
export declare const TourDismissButton1: PropDoc
export declare const useTourBeacon: PropDoc
export declare const useTourDialog: PropDoc
export declare const MotionBox2: PropDoc
export declare const useTour: PropDoc
export declare const PaddleScript: PropDoc
export declare const usePaddle: PropDoc
export declare const InlineCheckout: PropDoc
export declare const InlineCheckout1: PropDoc
export declare const usePaddle1: PropDoc
export declare const AppShell: PropDoc
export declare const AppShell1: PropDoc
export declare const ErrorBoundary: PropDoc
export declare const ErrorBoundary1: PropDoc
export declare const BulkActions: PropDoc
export declare const BulkActions1: PropDoc
export declare const DataGridPagination: PropDoc
export declare const DataGridProvider: PropDoc
export declare const DataGrid: PropDoc
export declare const DataGridSort: PropDoc
export declare const DataGridHeader: PropDoc
export declare const DefaultDataGridCell: PropDoc
export declare const useColumnVisibility: PropDoc
export declare const DataGridProvider1: PropDoc
export declare const DataGrid1: PropDoc
export declare const DataGridSort1: PropDoc
export declare const DataGridHeader1: PropDoc
export declare const DefaultDataGridCell1: PropDoc
export declare const useColumnVisibility1: PropDoc
export declare const DataGridPagination1: PropDoc
export declare const NoResults: PropDoc
export declare const NoResults1: PropDoc
export declare const ActiveFilter: PropDoc
export declare const ActiveFilterLabel: PropDoc
export declare const ActiveFilterOperator: PropDoc
export declare const ActiveFilterValue: PropDoc
export declare const ActiveFiltersList: PropDoc
export declare const FilterMenu: PropDoc
export declare const FiltersAddButton: PropDoc
export declare const FilterMenu1: PropDoc
export declare const ActiveFilter1: PropDoc
export declare const ActiveFilterLabel1: PropDoc
export declare const ActiveFilterOperator1: PropDoc
export declare const ActiveFilterValue1: PropDoc
export declare const ActiveFiltersList1: PropDoc
export declare const useActiveFilter: PropDoc
export declare const useFilterOperator: PropDoc
export declare const useFilterValue: PropDoc
export declare const FiltersProvider: PropDoc
export declare const NoFilteredResults: PropDoc
export declare const FiltersAddButton1: PropDoc
export declare const NoFilteredResults1: PropDoc
export declare const FiltersProvider1: PropDoc
export declare const useActiveFilter1: PropDoc
export declare const useFilterOperator1: PropDoc
export declare const useFilterValue1: PropDoc
export declare const useSearchQuery: PropDoc
export declare const useSteps: PropDoc
export declare const useSearchQuery1: PropDoc
export declare const useSteps1: PropDoc
export declare const ErrorBoundary2: PropDoc
export declare const AppShell2: PropDoc
export declare const BulkActions2: PropDoc
export declare const DataGridProvider2: PropDoc
export declare const DataGrid2: PropDoc
export declare const DataGridSort2: PropDoc
export declare const DataGridHeader2: PropDoc
export declare const DefaultDataGridCell2: PropDoc
export declare const useColumnVisibility2: PropDoc
export declare const DataGridPagination2: PropDoc
export declare const NoResults2: PropDoc
export declare const FilterMenu2: PropDoc
export declare const ActiveFilter2: PropDoc
export declare const ActiveFilterLabel2: PropDoc
export declare const ActiveFilterOperator2: PropDoc
export declare const ActiveFilterValue2: PropDoc
export declare const ActiveFiltersList2: PropDoc
export declare const useActiveFilter2: PropDoc
export declare const useFilterOperator2: PropDoc
export declare const useFilterValue2: PropDoc
export declare const FiltersProvider2: PropDoc
export declare const NoFilteredResults2: PropDoc
export declare const FiltersAddButton2: PropDoc
export declare const useSearchQuery2: PropDoc
export declare const useSteps2: PropDoc
export declare const PageHeader: PropDoc
export declare const PageBody: PropDoc
export declare const PageContainer: PropDoc
export declare const Page: PropDoc
export declare const ErrorPage: PropDoc
export declare const BackButton: PropDoc
export declare const Section: PropDoc
export declare const SectionContainer: PropDoc
export declare const SplitPage: PropDoc
export declare const PageSidebarContainer: PropDoc
export declare const PageSidebar: PropDoc
export declare const MenuListFilter: PropDoc
export declare const ResponsiveMenuList: PropDoc
export declare const MenuProperty: PropDoc
export declare const TenancyProvider: PropDoc
export declare const withThemeColors: PropDoc
export declare const ToolbarButton: PropDoc
export declare const ToolbarToggleButton: PropDoc
export declare const useResize: PropDoc
export declare const ResizeBox: PropDoc
export declare const Resizer: PropDoc
export declare const ToggleButtonGroup: PropDoc
export declare const ToggleButton: PropDoc
export declare const CheckboxButtonGroupField: PropDoc
export declare const RadioButtonGroupField: PropDoc
export declare const BenefitsModal2: PropDoc
export declare const BenefitsModalContainer2: PropDoc
export declare const BenefitsModalMedia2: PropDoc
export declare const BenefitsModalActions2: PropDoc
export declare const TourDialog2: PropDoc
export declare const TourDialogContainer2: PropDoc
export declare const TourDialogActions2: PropDoc
export declare const TourDialogPrimaryAction2: PropDoc
export declare const TourDialogSecondaryAction2: PropDoc
export declare const Tour2: PropDoc
export declare const TourNextButton2: PropDoc
export declare const TourPrevButton2: PropDoc
export declare const TourDismissButton2: PropDoc
export declare const MotionBox3: PropDoc
export declare const TourSpotlight2: PropDoc
export declare const MenuListFilter1: PropDoc
export declare const ResponsiveMenuList1: PropDoc
export declare const MenuProperty1: PropDoc
export declare const MenuListFilter2: PropDoc
export declare const MenuProperty2: PropDoc
export declare const ResponsiveMenuList2: PropDoc
export declare const useMenuFilterItem: PropDoc
export declare const actionmenu: PropDoc
export declare const BackButton1: PropDoc
export declare const ErrorPage1: PropDoc
export declare const PageHeader1: PropDoc
export declare const PageBody1: PropDoc
export declare const PageContainer1: PropDoc
export declare const Page1: PropDoc
export declare const ErrorPage2: PropDoc
export declare const BackButton2: PropDoc
export declare const Section1: PropDoc
export declare const SectionContainer1: PropDoc
export declare const SplitPage1: PropDoc
export declare const PageSidebarContainer1: PropDoc
export declare const PageSidebar1: PropDoc
export declare const PageSidebarContainer2: PropDoc
export declare const PageSidebar2: PropDoc
export declare const PageHeader2: PropDoc
export declare const PageBody2: PropDoc
export declare const PageContainer2: PropDoc
export declare const Page2: PropDoc
export declare const Section2: PropDoc
export declare const SectionContainer2: PropDoc
export declare const SplitPage2: PropDoc
export declare const useResize1: PropDoc
export declare const ResizeBox1: PropDoc
export declare const Resizer1: PropDoc
export declare const ResizeBox2: PropDoc
export declare const Resizer2: PropDoc
export declare const useResize2: PropDoc
export declare const TenancyProvider1: PropDoc
export declare const TenancyProvider2: PropDoc
export declare const withThemeColors1: PropDoc
export declare const withThemeColors2: PropDoc
export declare const ToggleButtonGroup1: PropDoc
export declare const ToggleButton1: PropDoc
export declare const CheckboxButtonGroupField1: PropDoc
export declare const RadioButtonGroupField1: PropDoc
export declare const ToggleButtonGroup2: PropDoc
export declare const ToggleButton2: PropDoc
export declare const CheckboxButtonGroupField2: PropDoc
export declare const RadioButtonGroupField2: PropDoc
export declare const useToggleGroup: PropDoc
export declare const ToolbarButton1: PropDoc
export declare const ToolbarToggleButton1: PropDoc
export declare const ToolbarButton2: PropDoc
export declare const ToolbarToggleButton2: PropDoc
export declare const MotionBox4: PropDoc
export declare const MotionBox5: PropDoc
export declare const createIcon: PropDoc
export declare const AppShell3: PropDoc
export declare const AppShell4: PropDoc
export declare const AuthForm: PropDoc
export declare const AuthFormDivider: PropDoc
export declare const LoginView: PropDoc
export declare const SignupView: PropDoc
export declare const OtpView: PropDoc
export declare const ForgotPasswordView: PropDoc
export declare const UpdatePasswordView: PropDoc
export declare const Auth: PropDoc
export declare const ForgotPasswordForm: PropDoc
export declare const Auth1: PropDoc
export declare const LoginButton: PropDoc
export declare const ProviderButton: PropDoc
export declare const AuthForm1: PropDoc
export declare const AuthFormDivider1: PropDoc
export declare const LoginView1: PropDoc
export declare const SignupView1: PropDoc
export declare const OtpView1: PropDoc
export declare const ForgotPasswordView1: PropDoc
export declare const UpdatePasswordView1: PropDoc
export declare const MagicLinkForm: PropDoc
export declare const PasswordForm: PropDoc
export declare const OtpForm: PropDoc
export declare const Providers: PropDoc
export declare const LoginButton1: PropDoc
export declare const MagicLinkForm1: PropDoc
export declare const OtpForm1: PropDoc
export declare const PasswordForm1: PropDoc
export declare const ProviderButton1: PropDoc
export declare const Providers1: PropDoc
export declare const AuthFormSuccess: PropDoc
export declare const UpdatePasswordForm: PropDoc
export declare const AuthProvider: PropDoc
export declare const useLogin: PropDoc
export declare const Auth2: PropDoc
export declare const LoginButton2: PropDoc
export declare const ProviderButton2: PropDoc
export declare const AuthForm2: PropDoc
export declare const AuthFormDivider2: PropDoc
export declare const LoginView2: PropDoc
export declare const SignupView2: PropDoc
export declare const OtpView2: PropDoc
export declare const ForgotPasswordView2: PropDoc
export declare const UpdatePasswordView2: PropDoc
export declare const MagicLinkForm2: PropDoc
export declare const PasswordForm2: PropDoc
export declare const OtpForm2: PropDoc
export declare const Providers2: PropDoc
export declare const AuthProvider1: PropDoc
export declare const useLogin1: PropDoc
export declare const BannerTransition: PropDoc
export declare const Banner: PropDoc
export declare const BannerIcon: PropDoc
export declare const Banner1: PropDoc
export declare const BannerIcon1: PropDoc
export declare const Button: PropDoc
export declare const Button1: PropDoc
export declare const Card: PropDoc
export declare const CardContainer: PropDoc
export declare const CardHeader: PropDoc
export declare const CardFooter: PropDoc
export declare const Card1: PropDoc
export declare const CardContainer1: PropDoc
export declare const CardHeader1: PropDoc
export declare const CardFooter1: PropDoc
export declare const RedirectToSignIn: PropDoc
export declare const RedirectToSignUp: PropDoc
export declare const AuthenticateWithRedirectCallback: PropDoc
export declare const SignUp: PropDoc
export declare const SignIn: PropDoc
export declare const UserProfile: PropDoc
export declare const UserButton: PropDoc
export declare const RedirectToSignIn1: PropDoc
export declare const RedirectToSignUp1: PropDoc
export declare const AuthenticateWithRedirectCallback1: PropDoc
export declare const SignInButton: PropDoc
export declare const SignUpButton: PropDoc
export declare const SignOutButton: PropDoc
export declare const SignInWithMetamaskButton: PropDoc
export declare const SignInButton1: PropDoc
export declare const SignInWithMetamaskButton1: PropDoc
export declare const SignOutButton1: PropDoc
export declare const SignUpButton1: PropDoc
export declare const SignIn1: PropDoc
export declare const SignUp1: PropDoc
export declare const UserProfile1: PropDoc
export declare const UserButton1: PropDoc
export declare const ClerkContextProvider: PropDoc
export declare const useOrganization: PropDoc
export declare const useMagicLink: PropDoc
export declare const useMagicLink1: PropDoc
export declare const useOrganization1: PropDoc
export declare const createGetToken: PropDoc
export declare const createSignOut: PropDoc
export declare const useMagicLink2: PropDoc
export declare const SignUp2: PropDoc
export declare const SignIn2: PropDoc
export declare const UserProfile2: PropDoc
export declare const UserButton2: PropDoc
export declare const RedirectToSignIn2: PropDoc
export declare const RedirectToSignUp2: PropDoc
export declare const AuthenticateWithRedirectCallback2: PropDoc
export declare const SignInButton2: PropDoc
export declare const SignUpButton2: PropDoc
export declare const SignOutButton2: PropDoc
export declare const SignInWithMetamaskButton2: PropDoc
export declare const useOrganization2: PropDoc
export declare const ClerkAuthProvider: PropDoc
export declare const ClerkAuthProvider1: PropDoc
export declare const Collapse: PropDoc
export declare const useCollapse: PropDoc
export declare const useCollapse1: PropDoc
export declare const DataTable: PropDoc
export declare const DataTableSort: PropDoc
export declare const DataTableHeader: PropDoc
export declare const DataTableCell: PropDoc
export declare const DataTable1: PropDoc
export declare const DataTableSort1: PropDoc
export declare const DataTableHeader1: PropDoc
export declare const DataTableCell1: PropDoc
export declare const jsonSchemaForm: PropDoc
export declare const jsonSchemaForm1: PropDoc
export declare const ArrayFieldRow: PropDoc
export declare const ArrayFieldRowFields: PropDoc
export declare const ArrayFieldRowContainer: PropDoc
export declare const ArrayFieldRemoveButton: PropDoc
export declare const ArrayFieldAddButton: PropDoc
export declare const ArrayField: PropDoc
export declare const ArrayFieldContainer: PropDoc
export declare const AutoForm: PropDoc
export declare const DisplayField: PropDoc
export declare const FormValue: PropDoc
export declare const DisplayIf: PropDoc
export declare const BaseField: PropDoc
export declare const Field: PropDoc
export declare const InputField: PropDoc
export declare const NumberInputField: PropDoc
export declare const PasswordInputField: PropDoc
export declare const TextareaField: PropDoc
export declare const SwitchField: PropDoc
export declare const SelectField: PropDoc
export declare const CheckboxField: PropDoc
export declare const RadioField: PropDoc
export declare const NativeSelectField: PropDoc
export declare const PinField: PropDoc
export declare const Fields: PropDoc
export declare const Form: PropDoc
export declare const useController: PropDoc
export declare const useFieldArray: PropDoc
export declare const useForm: PropDoc
export declare const useFormState: PropDoc
export declare const useWatch: PropDoc
export declare const DisplayField1: PropDoc
export declare const FormValue1: PropDoc
export declare const BaseField1: PropDoc
export declare const Field1: PropDoc
export declare const InputField1: PropDoc
export declare const NumberInputField1: PropDoc
export declare const PasswordInputField1: PropDoc
export declare const TextareaField1: PropDoc
export declare const SwitchField1: PropDoc
export declare const SelectField1: PropDoc
export declare const CheckboxField1: PropDoc
export declare const RadioField1: PropDoc
export declare const NativeSelectField1: PropDoc
export declare const PinField1: PropDoc
export declare const Fields1: PropDoc
export declare const Form1: PropDoc
export declare const AutoForm1: PropDoc
export declare const SubmitButton: PropDoc
export declare const ArrayFieldRow1: PropDoc
export declare const ArrayFieldRowFields1: PropDoc
export declare const ArrayFieldRowContainer1: PropDoc
export declare const ArrayFieldRemoveButton1: PropDoc
export declare const ArrayFieldAddButton1: PropDoc
export declare const ArrayField1: PropDoc
export declare const ArrayFieldContainer1: PropDoc
export declare const useArrayField: PropDoc
export declare const useArrayFieldRow: PropDoc
export declare const ObjectField: PropDoc
export declare const DisplayIf1: PropDoc
export declare const StepForm: PropDoc
export declare const FormStepper: PropDoc
export declare const FormStep: PropDoc
export declare const PrevButton: PropDoc
export declare const NextButton: PropDoc
export declare const useStepForm: PropDoc
export declare const useFormStep: PropDoc
export declare const WatchField: PropDoc
export declare const InputRightButton: PropDoc
export declare const ObjectField1: PropDoc
export declare const StepForm1: PropDoc
export declare const FormStepper1: PropDoc
export declare const FormStep1: PropDoc
export declare const PrevButton1: PropDoc
export declare const NextButton1: PropDoc
export declare const SubmitButton1: PropDoc
export declare const useArrayField1: PropDoc
export declare const useArrayFieldRow1: PropDoc
export declare const useStepForm1: PropDoc
export declare const useFormStep1: PropDoc
export declare const WatchField1: PropDoc
export declare const getFieldsFromSchema: PropDoc
export declare const yupFieldResolver: PropDoc
export declare const getFieldsFromSchema1: PropDoc
export declare const yupFieldResolver1: PropDoc
export declare const getFieldsFromSchema2: PropDoc
export declare const zodFieldResolver: PropDoc
export declare const zodMeta: PropDoc
export declare const getFieldsFromSchema3: PropDoc
export declare const zodFieldResolver1: PropDoc
export declare const zodMeta1: PropDoc
export declare const useSteps3: PropDoc
export declare const useSteps4: PropDoc
export declare const HotkeysList: PropDoc
export declare const HotkeysSearch: PropDoc
export declare const HotkeysGroup: PropDoc
export declare const HotkeysItem: PropDoc
export declare const HotkeysProvider: PropDoc
export declare const HotkeysList1: PropDoc
export declare const HotkeysSearch1: PropDoc
export declare const HotkeysGroup1: PropDoc
export declare const HotkeysItem1: PropDoc
export declare const HotkeysProvider1: PropDoc
export declare const InputRightButton1: PropDoc
export declare const InputRightButton2: PropDoc
export declare const Divider: PropDoc
export declare const EmptyState: PropDoc
export declare const EmptyStateContainer: PropDoc
export declare const EmptyStateBody: PropDoc
export declare const Divider1: PropDoc
export declare const EmptyState1: PropDoc
export declare const EmptyStateContainer1: PropDoc
export declare const EmptyStateBody1: PropDoc
export declare const Loader: PropDoc
export declare const Loading: PropDoc
export declare const Loader1: PropDoc
export declare const Loading1: PropDoc
export declare const List: PropDoc
export declare const ListHeader: PropDoc
export declare const ListItem: PropDoc
export declare const ListItemButton: PropDoc
export declare const ListItemIcon: PropDoc
export declare const ListItemLabel: PropDoc
export declare const ListItemTertiary: PropDoc
export declare const List1: PropDoc
export declare const ListHeader1: PropDoc
export declare const ListItem1: PropDoc
export declare const ListItemButton1: PropDoc
export declare const ListItemIcon1: PropDoc
export declare const ListItemLabel1: PropDoc
export declare const ListItemTertiary1: PropDoc
export declare const useContextMenu: PropDoc
export declare const MenuItem: PropDoc
export declare const OverflowMenu: PropDoc
export declare const useContextMenu1: PropDoc
export declare const MenuItem1: PropDoc
export declare const OverflowMenu1: PropDoc
export declare const ConfirmDialog: PropDoc
export declare const BaseDrawer: PropDoc
export declare const Drawer: PropDoc
export declare const FormDialog: PropDoc
export declare const ConfirmDialog1: PropDoc
export declare const BaseDrawer1: PropDoc
export declare const Drawer1: PropDoc
export declare const BaseModal: PropDoc
export declare const Modal: PropDoc
export declare const MenuDialog: PropDoc
export declare const MenuDialogList: PropDoc
export declare const FormDialog1: PropDoc
export declare const ModalsProvider: PropDoc
export declare const MenuDialog1: PropDoc
export declare const MenuDialogList1: PropDoc
export declare const BaseModal1: PropDoc
export declare const Modal1: PropDoc
export declare const ModalsProvider1: PropDoc
export declare const NProgress: PropDoc
export declare const NProgress1: PropDoc
export declare const NumberInput: PropDoc
export declare const NumberInput1: PropDoc
export declare const PasswordInput: PropDoc
export declare const PasswordInput1: PropDoc
export declare const Persona: PropDoc
export declare const PersonaContainer: PropDoc
export declare const PersonaAvatar: PropDoc
export declare const PersonaDetails: PropDoc
export declare const Persona1: PropDoc
export declare const PersonaContainer1: PropDoc
export declare const PersonaAvatar1: PropDoc
export declare const PersonaDetails1: PropDoc
export declare const PinInput: PropDoc
export declare const PinInput1: PropDoc
export declare const Property: PropDoc
export declare const PropertyLabel: PropDoc
export declare const Property1: PropDoc
export declare const PropertyLabel1: PropDoc
export declare const SaasProvider: PropDoc
export declare const SaasProvider1: PropDoc
export declare const RadioInput: PropDoc
export declare const RadioInput1: PropDoc
export declare const ErrorBoundary3: PropDoc
export declare const ErrorBoundary4: PropDoc
export declare const AuthProvider2: PropDoc
export declare const useLogin2: PropDoc
export declare const Auth3: PropDoc
export declare const LoginButton3: PropDoc
export declare const ProviderButton3: PropDoc
export declare const AuthForm3: PropDoc
export declare const AuthFormDivider3: PropDoc
export declare const LoginView3: PropDoc
export declare const SignupView3: PropDoc
export declare const OtpView3: PropDoc
export declare const ForgotPasswordView3: PropDoc
export declare const UpdatePasswordView3: PropDoc
export declare const MagicLinkForm3: PropDoc
export declare const PasswordForm3: PropDoc
export declare const OtpForm3: PropDoc
export declare const Providers3: PropDoc
export declare const Banner2: PropDoc
export declare const BannerIcon2: PropDoc
export declare const Button2: PropDoc
export declare const Card2: PropDoc
export declare const CardContainer2: PropDoc
export declare const CardHeader2: PropDoc
export declare const CardFooter2: PropDoc
export declare const Collapse1: PropDoc
export declare const useCollapse2: PropDoc
export declare const DataTable2: PropDoc
export declare const DataTableSort2: PropDoc
export declare const DataTableHeader2: PropDoc
export declare const DataTableCell2: PropDoc
export declare const List2: PropDoc
export declare const ListHeader2: PropDoc
export declare const ListItem2: PropDoc
export declare const ListItemButton2: PropDoc
export declare const ListItemIcon2: PropDoc
export declare const ListItemLabel2: PropDoc
export declare const ListItemTertiary2: PropDoc
export declare const Divider2: PropDoc
export declare const EmptyState2: PropDoc
export declare const EmptyStateContainer2: PropDoc
export declare const EmptyStateBody2: PropDoc
export declare const Loader2: PropDoc
export declare const Loading2: PropDoc
export declare const useController1: PropDoc
export declare const useFieldArray1: PropDoc
export declare const useForm1: PropDoc
export declare const useFormState1: PropDoc
export declare const useWatch1: PropDoc
export declare const DisplayField2: PropDoc
export declare const FormValue2: PropDoc
export declare const BaseField2: PropDoc
export declare const Field2: PropDoc
export declare const InputField2: PropDoc
export declare const NumberInputField2: PropDoc
export declare const PasswordInputField2: PropDoc
export declare const TextareaField2: PropDoc
export declare const SwitchField2: PropDoc
export declare const SelectField2: PropDoc
export declare const CheckboxField2: PropDoc
export declare const RadioField2: PropDoc
export declare const NativeSelectField2: PropDoc
export declare const PinField2: PropDoc
export declare const Fields2: PropDoc
export declare const Form2: PropDoc
export declare const AutoForm2: PropDoc
export declare const SubmitButton2: PropDoc
export declare const ArrayFieldRow2: PropDoc
export declare const ArrayFieldRowFields2: PropDoc
export declare const ArrayFieldRowContainer2: PropDoc
export declare const ArrayFieldRemoveButton2: PropDoc
export declare const ArrayFieldAddButton2: PropDoc
export declare const ArrayField2: PropDoc
export declare const ArrayFieldContainer2: PropDoc
export declare const useArrayField2: PropDoc
export declare const useArrayFieldRow2: PropDoc
export declare const ObjectField2: PropDoc
export declare const DisplayIf2: PropDoc
export declare const StepForm2: PropDoc
export declare const FormStepper2: PropDoc
export declare const FormStep2: PropDoc
export declare const PrevButton2: PropDoc
export declare const NextButton2: PropDoc
export declare const useStepForm2: PropDoc
export declare const useFormStep2: PropDoc
export declare const WatchField2: PropDoc
export declare const InputRightButton3: PropDoc
export declare const useSteps5: PropDoc
export declare const HotkeysProvider2: PropDoc
export declare const HotkeysList2: PropDoc
export declare const HotkeysSearch2: PropDoc
export declare const HotkeysGroup2: PropDoc
export declare const HotkeysItem2: PropDoc
export declare const MenuItem2: PropDoc
export declare const OverflowMenu2: PropDoc
export declare const useContextMenu2: PropDoc
export declare const ConfirmDialog2: PropDoc
export declare const BaseDrawer2: PropDoc
export declare const Drawer2: PropDoc
export declare const BaseModal2: PropDoc
export declare const Modal2: PropDoc
export declare const MenuDialog2: PropDoc
export declare const MenuDialogList2: PropDoc
export declare const FormDialog2: PropDoc
export declare const ModalsProvider2: PropDoc
export declare const NProgress2: PropDoc
export declare const NumberInput2: PropDoc
export declare const PasswordInput2: PropDoc
export declare const Persona2: PropDoc
export declare const PersonaContainer2: PropDoc
export declare const PersonaAvatar2: PropDoc
export declare const PersonaDetails2: PropDoc
export declare const PinInput2: PropDoc
export declare const Property2: PropDoc
export declare const PropertyLabel2: PropDoc
export declare const SaasProvider2: PropDoc
export declare const RadioInput2: PropDoc
export declare const SearchInput: PropDoc
export declare const Select: PropDoc
export declare const NativeSelect: PropDoc
export declare const useSnackbar: PropDoc
export declare const Stepper: PropDoc
export declare const StepperContainer: PropDoc
export declare const StepperSteps: PropDoc
export declare const StepperContent: PropDoc
export declare const StepperIcon: PropDoc
export declare const StepperStep: PropDoc
export declare const StepperSeparator: PropDoc
export declare const useStepper: PropDoc
export declare const useStep: PropDoc
export declare const usePrev: PropDoc
export declare const useNext: PropDoc
export declare const SearchInput1: PropDoc
export declare const SearchInput2: PropDoc
export declare const Select1: PropDoc
export declare const NativeSelect1: PropDoc
export declare const NativeSelect2: PropDoc
export declare const Select2: PropDoc
export declare const Sidebar: PropDoc
export declare const SidebarToggleButton: PropDoc
export declare const SidebarSection: PropDoc
export declare const Nav: PropDoc
export declare const NavGroupTitle: PropDoc
export declare const NavGroup: PropDoc
export declare const NavItem: PropDoc
export declare const NavGroupTitle1: PropDoc
export declare const Nav1: PropDoc
export declare const Sidebar1: PropDoc
export declare const useSnackbar1: PropDoc
export declare const useSnackbar2: PropDoc
export declare const Stepper1: PropDoc
export declare const StepperContainer1: PropDoc
export declare const StepperSteps1: PropDoc
export declare const StepperContent1: PropDoc
export declare const StepperIcon1: PropDoc
export declare const StepperStep1: PropDoc
export declare const StepperSeparator1: PropDoc
export declare const useStepper1: PropDoc
export declare const useStep1: PropDoc
export declare const usePrev1: PropDoc
export declare const useNext1: PropDoc
export declare const Stepper2: PropDoc
export declare const StepperContainer2: PropDoc
export declare const StepperSteps2: PropDoc
export declare const StepperContent2: PropDoc
export declare const StepperIcon2: PropDoc
export declare const StepperStep2: PropDoc
export declare const StepperSeparator2: PropDoc
export declare const useStepper2: PropDoc
export declare const useStep2: PropDoc
export declare const usePrev2: PropDoc
export declare const useNext2: PropDoc
export declare const Web3Address: PropDoc
export declare const Web3Address1: PropDoc
