// This file is generated by Velite

import type __vc from '../velite.config.ts'

type Collections = typeof __vc.collections

export type Docs = Collections['docs']['schema']['_output']
export declare const docs: Docs[]

export type Showcases = Collections['showcases']['schema']['_output']
export declare const showcases: Showcases[]

export type Notes = Collections['notes']['schema']['_output']
export declare const notes: Notes[]

export type Blog = Collections['blogs']['schema']['_output']
export declare const blogs: Blog[]
