import * as stylex from '@stylexjs/stylex'

export const lineHeights = stylex.defineVars({
  _2xs: 'calc(0.845rem * var(--scale-factor))',
  xs: 'calc(1rem * var(--scale-factor))',
  sm: 'calc(1.1375rem * var(--scale-factor))',
  md: 'calc(1.26rem * var(--scale-factor))',
  lg: 'calc(1.5rem * var(--scale-factor))',
  xl: 'calc(1.62rem * var(--scale-factor))',
  _2xl: 'calc(1.75rem * var(--scale-factor))',
  _3xl: 'calc(1.95rem * var(--scale-factor))',
  _4xl: 'calc(2.345rem * var(--scale-factor))',
  _5xl: 'calc(2.7rem * var(--scale-factor))',
  _6xl: 'calc(3.45rem * var(--scale-factor))',
  _7xl: 'calc(4.125rem * var(--scale-factor))',
  _8xl: 'calc(4.5rem * var(--scale-factor))',
  _9xl: 'calc(6rem * var(--scale-factor))',
  heading_xs: 'calc(0.95rem * var(--scale-factor))',
  heading_sm: 'calc(1rem * var(--scale-factor))',
  heading_md: 'calc(1.20rem * var(--scale-factor))',
  heading_lg: 'calc(1.33rem * var(--scale-factor))',
  heading_xl: 'calc(1.46rem * var(--scale-factor))',
  heading_2xl: 'calc(1.55rem * var(--scale-factor))',
  heading_3xl: 'calc(1.8rem * var(--scale-factor))',
  heading_4xl: 'calc(2.15rem * var(--scale-factor))',
  heading_5xl: 'calc(2.475rem * var(--scale-factor))',
  heading_6xl: 'calc(3rem * var(--scale-factor))',
  heading_7xl: 'calc(3.75rem * var(--scale-factor))',
})
