import * as stylex from '@stylexjs/stylex'

export const spacing = stylex.defineVars({
  _1: 'calc(0.25rem * var(--scale-factor))',
  _2: 'calc(0.5rem * var(--scale-factor))',
  _3: 'calc(0.75rem * var(--scale-factor))',
  _4: 'calc(1rem * var(--scale-factor))',
  _5: 'calc(1.25rem * var(--scale-factor))',
  _6: 'calc(1.5rem * var(--scale-factor))',
  _7: 'calc(1.75rem * var(--scale-factor))',
  _8: 'calc(2rem * var(--scale-factor))',
  _9: 'calc(2.25rem * var(--scale-factor))',
  _10: 'calc(2.5rem * var(--scale-factor))',
  _12: 'calc(3rem * var(--scale-factor))',
  _14: 'calc(3.5rem * var(--scale-factor))',
  _16: 'calc(4rem * var(--scale-factor))',
  _20: 'calc(5rem * var(--scale-factor))',
  _24: 'calc(6rem * var(--scale-factor))',
  _28: 'calc(7rem * var(--scale-factor))',
  _32: 'calc(8rem * var(--scale-factor))',
  _36: 'calc(9rem * var(--scale-factor))',
  _40: 'calc(10rem * var(--scale-factor))',
  _44: 'calc(11rem * var(--scale-factor))',
  _48: 'calc(12rem * var(--scale-factor))',
  _52: 'calc(13rem * var(--scale-factor))',
  _56: 'calc(14rem * var(--scale-factor))',
  _60: 'calc(15rem * var(--scale-factor))',
  _64: 'calc(16rem * var(--scale-factor))',
  _72: 'calc(18rem * var(--scale-factor))',
  _80: 'calc(20rem * var(--scale-factor))',
  _96: 'calc(24rem * var(--scale-factor))',
  _0_5: 'calc(0.125rem * var(--scale-factor))',
  _1_5: 'calc(0.375rem * var(--scale-factor))',
  _2_5: 'calc(0.625rem * var(--scale-factor))',
  _3_5: 'calc(0.875rem * var(--scale-factor))',
  _4_5: 'calc(1.125rem * var(--scale-factor))',
})
