export {
  DialogRoot as Root,
  DialogContent as Content,
  DialogCloseButton as CloseButton,
  DialogCloseTrigger as CloseTrigger,
  DialogHeader as Header,
  DialogBody as Body,
  DialogFooter as Footer,
  DialogActionTrigger as ActionTrigger,
  DialogBackdrop as Backdrop,
  DialogDescription as Description,
  DialogTitle as Title,
  DialogTrigger as Trigger,
  DialogContext as Context,
} from './dialog.tsx'
export type {
  DialogContentProps as ContentProps,
  DialogRootProps as RootProps,
} from './dialog.tsx'
