import { createHash, randomUUID } from 'node:crypto'
import {
  cp,
  lstat,
  mkdir,
  readFile,
  readdir,
  rename,
  rm,
  writeFile,
} from 'node:fs/promises'
import path from 'node:path'
import { z } from 'zod'

import {
  REGISTRY_SCHEMA_VERSION,
  type RegistryItem,
  componentsConfigSchema,
  registryIndexSchema,
  registryItemSchema,
  registrySchema,
} from '../schema.js'
import type {
  RegistryCompilerDiagnostic,
  RegistryDependencyGraph,
  ResolvedRegistryItem,
} from './model.js'
import {
  isRegistryNonInstallableSource,
  isRegistryPreviewSource,
  isRegistryTypeTestSource,
} from './path-utils.js'

const generatedBanner = `// @ts-nocheck
// This file is generated by @saas-ui/registry/compiler.
// Do not edit this file directly.
`

const installableItemTypes = new Set([
  'registry:setup',
  'registry:ui',
  'registry:component',
  'registry:lib',
  'registry:hook',
  'registry:icon',
  'registry:block',
])

export interface EmitRegistryDiagnostic {
  code: string
  message: string
  severity: 'error' | 'warning' | 'info'
  stage?: RegistryCompilerDiagnostic['stage']
  item?: string
  file?: string
  moduleSpecifier?: string
  dependency?: string
}

export interface EmitRegistryFile {
  path: string
  content: string
  type?: RegistryItem['type']
  target?: string
  /** Static AST proof supplied by the analysis stage. */
  hasRenderableDefaultExport?: boolean
}

export interface EmitRegistryPreview {
  path: string
  /** React.lazy requires a renderable component at module.default. */
  hasRenderableDefaultExport: boolean
}

/**
 * The small structural contract between the compiler pipeline and emitter.
 * RegistryDependencyGraph is assignable to this type without the emitter
 * depending on discovery or analysis implementation details.
 */
export interface EmitRegistryItem extends Omit<
  RegistryItem,
  'files' | 'schemaVersion'
> {
  files: EmitRegistryFile[]
  /** Explicit preview path relative to the registry style root. */
  preview?: string
  /** Analysis of an explicit preview, including excluded example files. */
  previewAnalysis?: EmitRegistryPreview
  /** Primary source path relative to the registry style root. */
  primaryFile?: string
}

export interface EmitRegistryInput {
  name?: string
  homepage?: string
  items: readonly EmitRegistryItem[]
  diagnostics?: readonly EmitRegistryDiagnostic[]
  iconMetadata?: Readonly<Record<string, unknown>>
  iconLibraries?: Readonly<
    Record<string, Readonly<{ import?: string; package?: string }>>
  >
}

export interface RegistryArtifact {
  /** POSIX path relative to outputDir. */
  path: string
  content: string
  sha256: string
}

export interface RegistryArtifacts {
  files: readonly RegistryArtifact[]
  contentHashes: Readonly<Record<string, string>>
  validationReport: RegistryValidationArtifact
}

export interface RegistryValidationArtifact {
  schemaVersion: typeof REGISTRY_SCHEMA_VERSION
  valid: boolean
  errors: number
  warnings: number
  infos: number
  items: number
  diagnostics: readonly EmitRegistryDiagnostic[]
  contentHashes: Readonly<Record<string, string>>
}

export interface EmitRegistryOptions {
  /** Write artifacts when provided; omission keeps the operation pure. */
  outputDir?: string
  /** Directory for the generated preview index. Defaults to outputDir. */
  previewOutputDir?: string
  style?: {
    name: string
    label: string
  }
  /** Import prefix used by the website preview index. */
  previewImportPrefix?: string
  /** Controls the writer transaction. Primarily exposed for bounded waits and tests. */
  transaction?: RegistryTransactionOptions
}

export type RegistryTransactionPhase =
  | 'locked'
  | 'staged'
  | 'before-commit'
  | 'public-committed'
  | 'preview-committed'
  | 'committed'
  | 'rollback'

export interface RegistryTransactionOptions {
  /** Maximum time to wait for another generator. Defaults to 30 seconds. */
  lockTimeoutMs?: number
  /** Poll interval while another generator holds the lock. Defaults to 25ms. */
  lockPollMs?: number
  /** Age after which an unreadable lock is recoverable. Defaults to 5 minutes. */
  staleLockMs?: number
  /** Transaction lifecycle hook used for observability and fault injection. */
  onPhase?: (phase: RegistryTransactionPhase) => void | Promise<void>
}

interface NormalizedRegistryItem extends Omit<
  RegistryItem,
  'files' | 'schemaVersion'
> {
  schemaVersion: typeof REGISTRY_SCHEMA_VERSION
  files: EmitRegistryFile[]
  preview?: string
  previewAnalysis?: EmitRegistryPreview
  primaryFile?: string
}

function sha256(value: string) {
  return createHash('sha256').update(value).digest('hex')
}

function normalizeNewline(value: string) {
  return `${value.replace(/\r\n?/g, '\n').replace(/\n*$/, '')}\n`
}

function compareText(left: string, right: string) {
  return left.localeCompare(right, 'en')
}

function sortRecord(value: unknown): unknown {
  if (Array.isArray(value)) {
    return value.map(sortRecord)
  }

  if (!value || typeof value !== 'object') {
    return value
  }

  return Object.fromEntries(
    Object.entries(value)
      .sort(([left], [right]) => compareText(left, right))
      .map(([key, child]) => [key, sortRecord(child)]),
  )
}

function json(value: unknown) {
  return `${JSON.stringify(sortRecord(value), null, 2)}\n`
}

function uniqueSorted(values: readonly string[] | undefined) {
  return values ? [...new Set(values)].sort(compareText) : undefined
}

function normalizeFile(
  file: EmitRegistryFile,
  fallbackType: RegistryItem['type'],
): EmitRegistryFile & { type: RegistryItem['type'] } {
  const normalized: EmitRegistryFile & { type: RegistryItem['type'] } = {
    path: file.path.split(path.sep).join('/'),
    type: file.type ?? fallbackType,
    content: normalizeNewline(file.content),
  }

  if (file.target) {
    normalized.target = file.target.split(path.sep).join('/')
  }
  if (file.hasRenderableDefaultExport !== undefined) {
    normalized.hasRenderableDefaultExport = file.hasRenderableDefaultExport
  }

  return normalized
}

function normalizeItem(item: EmitRegistryItem): NormalizedRegistryItem {
  const normalized: NormalizedRegistryItem = {
    schemaVersion: REGISTRY_SCHEMA_VERSION,
    name: item.name,
    type: item.type,
    files: item.files
      .filter(
        (file) =>
          isRegistryNonInstallableSource(file.path, {
            allowExample: !installableItemTypes.has(item.type),
          }) === false,
      )
      .map((file) => normalizeFile(file, item.type))
      .sort((left, right) => compareText(left.path, right.path)),
  }

  if (item.version) normalized.version = item.version
  if (item.private !== undefined) normalized.private = item.private
  if (item.description) normalized.description = item.description
  if (item.source) normalized.source = item.source
  if (item.order !== undefined) normalized.order = item.order
  if (item.dependencies?.length)
    normalized.dependencies = uniqueSorted(item.dependencies)
  if (item.devDependencies?.length)
    normalized.devDependencies = uniqueSorted(item.devDependencies)
  if (item.registryDependencies?.length)
    normalized.registryDependencies = uniqueSorted(item.registryDependencies)
  if (item.tailwind) normalized.tailwind = sortRecord(item.tailwind) as never
  if (item.cssVars) normalized.cssVars = sortRecord(item.cssVars) as never
  if (item.category) normalized.category = item.category
  if (item.categories?.length)
    normalized.categories = uniqueSorted(item.categories)
  if (item.subcategory) normalized.subcategory = item.subcategory
  if (item.chunks?.length)
    normalized.chunks = item.chunks.map((chunk) => sortRecord(chunk) as never)
  if (item.meta) normalized.meta = sortRecord(item.meta) as never
  if (item.canvas) normalized.canvas = sortRecord(item.canvas) as never
  if (item.docs) normalized.docs = item.docs
  if (item.preview) normalized.preview = item.preview
  if (item.previewAnalysis) {
    normalized.previewAnalysis = {
      path: item.previewAnalysis.path.split(path.sep).join('/'),
      hasRenderableDefaultExport:
        item.previewAnalysis.hasRenderableDefaultExport,
    }
  }
  if (item.primaryFile) normalized.primaryFile = item.primaryFile

  return normalized
}

function itemPayload(item: NormalizedRegistryItem) {
  const {
    preview,
    previewAnalysis: _previewAnalysis,
    primaryFile: _primaryFile,
    files,
    ...payload
  } = item
  return {
    ...payload,
    ...(preview && !isRegistryPreviewSource(preview) ? { preview } : {}),
    files: files.map(
      ({ hasRenderableDefaultExport: _hasRenderableDefaultExport, ...file }) =>
        file,
    ),
  }
}

function itemHash(item: NormalizedRegistryItem) {
  const { preview: _preview, ...payload } = itemPayload(item)
  return sha256(json(payload))
}

function withContentHash(item: NormalizedRegistryItem) {
  const contentHash = itemHash(item)
  const payload = itemPayload(item)

  return {
    ...payload,
    meta: {
      ...(payload.meta ?? {}),
      contentHash,
    },
  }
}

function createJsonSchema(schema: z.ZodType, id: string) {
  return {
    ...z.toJSONSchema(schema, {
      io: 'output',
      target: 'draft-2020-12',
      unrepresentable: 'any',
    }),
    $id: id,
    'x-registry-schema-version': REGISTRY_SCHEMA_VERSION,
  }
}

function toIndexItem(item: NormalizedRegistryItem) {
  const payload = withContentHash(item)

  return {
    ...payload,
    files: payload.files.map(({ content: _content, ...file }) => file),
  }
}

interface PreviewSelection {
  hasRenderableDefaultExport: boolean
  path: string
  selection: 'preview' | 'primary-file' | 'convention'
}

function findItemFile(item: NormalizedRegistryItem, selected: string) {
  const normalized = selected.replace(/^\.\//, '')
  return item.files.find(
    (file) => file.path === normalized || file.path.endsWith(`/${normalized}`),
  )
}

function selectPreviewFile(
  item: NormalizedRegistryItem,
): PreviewSelection | undefined {
  if (item.previewAnalysis) {
    return { ...item.previewAnalysis, selection: 'preview' }
  }

  if (item.preview && !isRegistryPreviewSource(item.preview)) {
    return undefined
  }

  const selected = item.preview ?? item.primaryFile
  if (selected) {
    const normalized = selected.replace(/^\.\//, '')
    const file = findItemFile(item, normalized)
    return {
      path: file?.path ?? normalized,
      hasRenderableDefaultExport: file?.hasRenderableDefaultExport === true,
      selection: item.preview ? 'preview' : 'primary-file',
    }
  }

  const expectedBasename = `${item.name}.tsx`
  const file = item.files.find(
    (file) => path.posix.basename(file.path) === expectedBasename,
  )
  return file
    ? {
        path: file.path,
        hasRenderableDefaultExport: file.hasRenderableDefaultExport === true,
        selection: 'convention',
      }
    : undefined
}

function createPreviewIndex(
  items: readonly NormalizedRegistryItem[],
  styleName: string,
  importPrefix: string,
) {
  const diagnostics: EmitRegistryDiagnostic[] = []
  const entries = items.flatMap((item) => {
    if (
      !['registry:ui', 'registry:block', 'registry:example'].includes(item.type)
    ) {
      return []
    }

    const previewCandidate = selectPreviewFile(item)
    const externalPreview =
      item.preview && !isRegistryPreviewSource(item.preview)
        ? item.preview
        : undefined
    if (previewCandidate && isRegistryTypeTestSource(previewCandidate.path)) {
      diagnostics.push({
        code: 'preview-type-test-source',
        message: `Preview candidate "${previewCandidate.path}" is a type-test source and cannot be rendered`,
        severity: 'error',
        item: item.name,
        file: previewCandidate.path,
      })
    }
    const previewFile =
      previewCandidate && !isRegistryTypeTestSource(previewCandidate.path)
        ? previewCandidate
        : undefined
    if (previewFile && !previewFile.hasRenderableDefaultExport) {
      diagnostics.push({
        code: 'preview-default-export-not-renderable',
        message: `Preview candidate "${previewFile.path}" does not have a statically proven renderable default export; its lazy component was omitted`,
        severity:
          previewFile.selection === 'preview'
            ? 'error'
            : previewFile.selection === 'primary-file'
              ? 'warning'
              : 'info',
        item: item.name,
        file: previewFile.path,
      })
    }

    return [
      `    ${JSON.stringify(item.name)}: {\n` +
        `      name: ${JSON.stringify(item.name)},\n` +
        `      type: ${JSON.stringify(item.type)},\n` +
        `      registryDependencies: ${JSON.stringify(
          item.registryDependencies ?? [],
        )},\n` +
        `      files: ${JSON.stringify(
          item.files.map((file) => `../${file.path}`),
        )},\n` +
        (externalPreview || previewFile
          ? `      preview: ${JSON.stringify(externalPreview ?? previewFile?.path)},\n`
          : '') +
        (previewFile?.hasRenderableDefaultExport
          ? `      component: React.lazy(() => import(${JSON.stringify(
              `${importPrefix}/${previewFile.path}`,
            )})),\n`
          : '') +
        `      source: ${JSON.stringify(item.source ?? '')},\n` +
        `      categories: ${item.categories ? JSON.stringify(item.categories) : 'undefined'},\n` +
        `      chunks: ${JSON.stringify(item.chunks ?? [])},\n` +
        `    },`,
    ]
  })

  return {
    content: normalizeNewline(`${generatedBanner}import * as React from 'react'

export const Index: Record<string, any> = {
  ${JSON.stringify(styleName)}: {
${entries.join('\n')}
  },
}
`),
    diagnostics,
  }
}

function createIconPreviewIndex(
  iconMetadata: Readonly<Record<string, unknown>> | undefined,
  iconLibraries:
    | Readonly<Record<string, Readonly<{ import?: string; package?: string }>>>
    | undefined,
) {
  const icons = Object.entries(iconMetadata ?? {}).sort(([left], [right]) =>
    compareText(left, right),
  )
  const entries = icons.map(([iconName, value]) => {
    const libraries =
      value && typeof value === 'object'
        ? Object.entries(value as Record<string, unknown>).sort(
            ([left], [right]) => compareText(left, right),
          )
        : []
    const variants = libraries.flatMap(([library, componentName]) => {
      if (typeof componentName !== 'string') return []
      const moduleName =
        iconLibraries?.[library]?.import ?? iconLibraries?.[library]?.package
      if (!moduleName) return []
      return [
        `    ${JSON.stringify(library)}: React.lazy(() => import(${JSON.stringify(
          moduleName,
        )}).then((module) => ({ default: module[${JSON.stringify(
          componentName,
        )}] }))),`,
      ]
    })

    return `  ${JSON.stringify(iconName)}: {\n${variants.join('\n')}\n  },`
  })

  return normalizeNewline(`${generatedBanner}import * as React from 'react'

export const Icons = {
${entries.join('\n')}
}
`)
}

function normalizeDiagnostic(
  diagnostic: EmitRegistryDiagnostic,
): EmitRegistryDiagnostic {
  const result: EmitRegistryDiagnostic = {
    code: diagnostic.code,
    message: diagnostic.message,
    severity: diagnostic.severity,
  }

  if (diagnostic.stage) result.stage = diagnostic.stage
  if (diagnostic.item) result.item = diagnostic.item
  if (diagnostic.file) result.file = diagnostic.file
  if (diagnostic.moduleSpecifier)
    result.moduleSpecifier = diagnostic.moduleSpecifier
  if (diagnostic.dependency) result.dependency = diagnostic.dependency
  return result
}

function compareDiagnostics(
  left: EmitRegistryDiagnostic,
  right: EmitRegistryDiagnostic,
) {
  return compareText(
    [
      left.severity,
      left.stage,
      left.code,
      left.item,
      left.file,
      left.message,
    ].join(':'),
    [
      right.severity,
      right.stage,
      right.code,
      right.item,
      right.file,
      right.message,
    ].join(':'),
  )
}

function compilerDiagnosticToEmitDiagnostic(
  diagnostic: RegistryCompilerDiagnostic,
): EmitRegistryDiagnostic {
  return {
    code: diagnostic.code,
    message: diagnostic.message,
    severity: diagnostic.severity,
    stage: diagnostic.stage,
    item: diagnostic.itemName,
    file: diagnostic.filePath,
    moduleSpecifier: diagnostic.moduleSpecifier,
    dependency: diagnostic.dependency,
  }
}

function toPascalCase(value: string) {
  return value
    .split(/[^a-zA-Z0-9]+/)
    .filter(Boolean)
    .map((part) => `${part[0]?.toUpperCase()}${part.slice(1)}`)
    .join('')
}

function toKebabCase(value: string) {
  return value
    .replace(/([a-z0-9])([A-Z])/g, '$1-$2')
    .replace(/[^a-zA-Z0-9]+/g, '-')
    .toLowerCase()
}

/** Create per-item metadata from the checked-in registry icon catalog. */
export function createIconItemMetadata(
  iconMetadata: Readonly<Record<string, unknown>>,
  defaultIconSet = 'lucide',
) {
  return Object.fromEntries(
    Object.entries(iconMetadata)
      .sort(([left], [right]) => compareText(left, right))
      .flatMap(([name, value]) => {
        if (!value || typeof value !== 'object') return []
        const iconName = Reflect.get(value, defaultIconSet)
        if (typeof iconName !== 'string') return []
        return [
          [
            `${toKebabCase(name)}-icon`,
            {
              componentName: `${name}Icon`,
              iconSet: defaultIconSet,
              iconName,
            },
          ] as const,
        ]
      }),
  )
}

function reconcileIconCatalog(
  items: readonly EmitRegistryItem[],
  iconMetadata: Readonly<Record<string, unknown>> | undefined,
) {
  if (!iconMetadata) {
    return { items, diagnostics: [] as EmitRegistryDiagnostic[] }
  }

  const diagnostics: EmitRegistryDiagnostic[] = []
  const catalogItems = createIconItemMetadata(iconMetadata)
  const expectedNames = new Set(Object.keys(catalogItems))
  const discoveredIcons = items.filter((item) => item.type === 'registry:icon')
  const discoveredNames = new Set(discoveredIcons.map((item) => item.name))

  for (const catalogName of Object.keys(iconMetadata).sort(compareText)) {
    if (`${toKebabCase(catalogName)}-icon` in catalogItems) continue
    diagnostics.push({
      code: 'icon-catalog-entry-invalid',
      message: `Icon catalog entry "${catalogName}" has no usable default icon mapping`,
      severity: 'error',
      item: catalogName,
    })
  }

  for (const expectedName of [...expectedNames].sort(compareText)) {
    if (discoveredNames.has(expectedName)) continue
    diagnostics.push({
      code: 'icon-catalog-source-missing',
      message: `Icon catalog item "${expectedName}" has no discovered checked-in source`,
      severity: 'error',
      item: expectedName,
    })
  }

  for (const item of discoveredIcons.sort((left, right) =>
    compareText(left.name, right.name),
  )) {
    if (expectedNames.has(item.name)) continue
    diagnostics.push({
      code: 'icon-source-not-in-catalog',
      message: `Discovered icon source "${item.name}" is not represented by the static icon catalog and will not be emitted`,
      severity: 'error',
      item: item.name,
    })
  }

  return {
    items: items.filter(
      (item) => item.type !== 'registry:icon' || expectedNames.has(item.name),
    ),
    diagnostics,
  }
}

function configuredSourcePath(
  item: ResolvedRegistryItem,
  value: string | undefined,
) {
  if (!value) return undefined
  const normalized = value.replace(/^\.\//, '')
  if (path.isAbsolute(normalized)) {
    return path
      .relative(item.sourceBasePath, normalized)
      .split(path.sep)
      .join('/')
  }
  if (
    normalized === item.relativeDirectory ||
    normalized.startsWith(`${item.relativeDirectory}/`)
  ) {
    return normalized
  }
  return path.posix.join(item.relativeDirectory, normalized)
}

function resolvedItemToEmitItem(
  item: ResolvedRegistryItem,
  metadataOverride: Readonly<Record<string, unknown>> | undefined,
): EmitRegistryItem {
  const inferredIconMetadata =
    item.type === 'registry:icon'
      ? {
          componentName: toPascalCase(item.name),
          iconName: toPascalCase(item.name).replace(/Icon$/, ''),
          iconSet: 'checked-in',
        }
      : undefined
  const authoredCompilerMetadata = item.metadata.meta?.compiler
  const compilerMetadata = {
    client: item.client,
    fileHashes: Object.fromEntries(
      item.files
        .map((file) => [file.path, file.hash] as const)
        .sort(([left], [right]) => compareText(left, right)),
    ),
    iconDependencies: item.iconDependencies,
    presetImports: item.presetImports,
    recipeReferences: item.recipeReferences,
    presetRecipeBindings: item.presetRecipeBindings,
    ...(authoredCompilerMetadata === undefined
      ? {}
      : { authored: authoredCompilerMetadata }),
  }

  return {
    name: item.name,
    type: item.type,
    version: item.metadata.version,
    private: item.metadata.private,
    description: item.metadata.description,
    dependencies: item.dependencies,
    devDependencies: item.devDependencies,
    registryDependencies: item.registryDependencies,
    source: item.metadata.source,
    order: item.metadata.order,
    categories: item.metadata.categories,
    category: item.metadata.category,
    subcategory: item.metadata.subcategory,
    chunks: item.metadata.chunks,
    meta:
      inferredIconMetadata || metadataOverride || item.metadata.meta
        ? {
            ...inferredIconMetadata,
            ...metadataOverride,
            ...item.metadata.meta,
            compiler: compilerMetadata,
          }
        : { compiler: compilerMetadata },
    canvas: item.metadata.canvas,
    docs: item.metadata.docs,
    preview: item.previewAnalysis
      ? configuredSourcePath(item, item.metadata.preview)
      : item.metadata.preview,
    previewAnalysis: item.previewAnalysis
      ? {
          path: item.previewAnalysis.path,
          hasRenderableDefaultExport:
            item.previewAnalysis.hasRenderableDefaultExport,
        }
      : undefined,
    primaryFile: configuredSourcePath(item, item.metadata.primaryFile),
    files: item.files.map((file) => ({
      path: file.path,
      content: file.content,
      type: file.type ?? item.type,
      target: file.target,
      hasRenderableDefaultExport: file.hasRenderableDefaultExport,
    })),
  }
}

export interface CreateEmitRegistryInputOptions {
  name?: string
  homepage?: string
  iconMetadata?: Readonly<Record<string, unknown>>
  iconLibraries?: Readonly<
    Record<string, Readonly<{ import?: string; package?: string }>>
  >
  iconItemMetadata?: Readonly<Record<string, Readonly<Record<string, unknown>>>>
  diagnostics?: readonly RegistryCompilerDiagnostic[]
}

/** Adapt the normalized graph without making it another source of truth. */
export function createEmitRegistryInput(
  graph: RegistryDependencyGraph,
  options: CreateEmitRegistryInputOptions = {},
): EmitRegistryInput {
  return {
    name: options.name,
    homepage: options.homepage,
    items: graph.items.map((item) =>
      resolvedItemToEmitItem(item, options.iconItemMetadata?.[item.name]),
    ),
    diagnostics: (options.diagnostics ?? graph.diagnostics).map(
      compilerDiagnosticToEmitDiagnostic,
    ),
    iconMetadata: options.iconMetadata,
    iconLibraries: options.iconLibraries,
  }
}

function addArtifact(
  target: Map<string, RegistryArtifact>,
  artifactPath: string,
  content: string,
) {
  const normalizedPath = normalizeManagedRelativePath(artifactPath)
  if (!normalizedPath) {
    throw new TypeError(
      `Registry artifact path must stay within its output root: ${artifactPath}`,
    )
  }
  const normalizedContent = normalizeNewline(content)
  target.set(normalizedPath, {
    path: normalizedPath,
    content: normalizedContent,
    sha256: sha256(normalizedContent),
  })
}

/** Build every public registry artifact without touching the filesystem. */
export function createRegistryArtifacts(
  input: EmitRegistryInput,
  options: Omit<EmitRegistryOptions, 'outputDir' | 'previewOutputDir'> = {},
): RegistryArtifacts {
  const style = options.style ?? { name: 'default', label: 'Default' }
  const previewImportPrefix =
    options.previewImportPrefix ?? `@/registry/${style.name}`
  const iconCatalog = reconcileIconCatalog(input.items, input.iconMetadata)
  const items = iconCatalog.items
    .map(normalizeItem)
    .sort(
      (left, right) =>
        (left.order ?? Number.POSITIVE_INFINITY) -
          (right.order ?? Number.POSITIVE_INFINITY) ||
        compareText(left.name, right.name),
    )
  const artifacts = new Map<string, RegistryArtifact>()
  const contentHashes = Object.fromEntries(
    items.map((item) => [item.name, itemHash(item)]),
  )

  const installableItems = items.filter((item) =>
    installableItemTypes.has(item.type),
  )

  addArtifact(artifacts, 'index.json', json(installableItems.map(toIndexItem)))
  addArtifact(artifacts, 'styles/index.json', json([style]))
  addArtifact(
    artifacts,
    `styles/${style.name}/index.json`,
    json({
      schemaVersion: REGISTRY_SCHEMA_VERSION,
      name: style.name,
      type: 'registry:style',
      dependencies: [],
      registryDependencies: [],
      cssVars: {},
      files: [],
    }),
  )

  for (const item of installableItems) {
    addArtifact(
      artifacts,
      `styles/${style.name}/${item.name}.json`,
      json(withContentHash(item)),
    )
  }

  addArtifact(
    artifacts,
    'schema/components.json',
    json(
      createJsonSchema(
        componentsConfigSchema,
        `${input.homepage ?? 'https://saas-ui.dev'}/r/schema/components.json`,
      ),
    ),
  )
  addArtifact(
    artifacts,
    'schema/registry-item.json',
    json(
      createJsonSchema(
        registryItemSchema,
        `${input.homepage ?? 'https://saas-ui.dev'}/r/schema/registry-item.json`,
      ),
    ),
  )
  addArtifact(
    artifacts,
    'schema/registry.json',
    json(
      createJsonSchema(
        registrySchema,
        `${input.homepage ?? 'https://saas-ui.dev'}/r/schema/registry.json`,
      ),
    ),
  )
  addArtifact(
    artifacts,
    'schema/registry-index.json',
    json(
      createJsonSchema(
        registryIndexSchema,
        `${input.homepage ?? 'https://saas-ui.dev'}/r/schema/registry-index.json`,
      ),
    ),
  )

  const iconItems = items.filter((item) => item.type === 'registry:icon')
  const inferredIconMetadata = Object.fromEntries(
    iconItems.map((item) => [
      item.name,
      {
        ...(item.meta ?? {}),
        contentHash: contentHashes[item.name],
      },
    ]),
  )
  addArtifact(
    artifacts,
    'icons/index.json',
    json(input.iconMetadata ?? inferredIconMetadata),
  )

  const previewIndex = createPreviewIndex(
    items,
    style.name,
    previewImportPrefix,
  )
  addArtifact(artifacts, '__registry__/index.tsx', previewIndex.content)
  addArtifact(
    artifacts,
    '__registry__/icons.tsx',
    createIconPreviewIndex(input.iconMetadata, input.iconLibraries),
  )

  const diagnostics = [
    ...(input.diagnostics ?? []),
    ...iconCatalog.diagnostics,
    ...previewIndex.diagnostics,
  ]
    .map(normalizeDiagnostic)
    .sort(compareDiagnostics)
  const validationReport: RegistryValidationArtifact = {
    schemaVersion: REGISTRY_SCHEMA_VERSION,
    valid: !diagnostics.some((diagnostic) => diagnostic.severity === 'error'),
    errors: diagnostics.filter((diagnostic) => diagnostic.severity === 'error')
      .length,
    warnings: diagnostics.filter(
      (diagnostic) => diagnostic.severity === 'warning',
    ).length,
    infos: diagnostics.filter((diagnostic) => diagnostic.severity === 'info')
      .length,
    items: items.length,
    diagnostics,
    contentHashes,
  }
  addArtifact(artifacts, 'validation-report.json', json(validationReport))

  return {
    files: [...artifacts.values()].sort((left, right) =>
      compareText(left.path, right.path),
    ),
    contentHashes,
    validationReport,
  }
}

async function writeAtomically(filename: string, content: string) {
  await mkdir(path.dirname(filename), { recursive: true })
  const temporary = `${filename}.${process.pid}.${randomUUID()}.tmp`
  try {
    await writeFile(temporary, content, 'utf8')
    await rename(temporary, filename)
  } finally {
    await rm(temporary, { force: true })
  }
}

interface RegistryArtifactManifest {
  found: boolean
  files: string[]
  previewFiles: string[]
}

function normalizeManagedRelativePath(value: string) {
  const posixValue = value.replaceAll('\\', '/')
  if (
    !posixValue ||
    path.posix.isAbsolute(posixValue) ||
    /^[a-zA-Z]:\//.test(posixValue)
  ) {
    return undefined
  }

  const normalized = path.posix.normalize(posixValue).replace(/^\.\//, '')
  if (!normalized || normalized === '.' || normalized.startsWith('../')) {
    return undefined
  }
  return normalized
}

function resolveManagedPath(root: string, relativePath: string) {
  const normalized = normalizeManagedRelativePath(relativePath)
  if (!normalized) return undefined

  const normalizedRoot = path.resolve(root)
  const resolved = path.resolve(normalizedRoot, ...normalized.split('/'))
  if (
    resolved !== normalizedRoot &&
    !resolved.startsWith(`${normalizedRoot}${path.sep}`)
  ) {
    return undefined
  }
  return { path: resolved, relativePath: normalized }
}

const registryPathSegmentPattern = /^[a-z0-9](?:[a-z0-9._-]*[a-z0-9])?$/

function isManagedPublicArtifactPath(relativePath: string) {
  if (
    relativePath === 'index.json' ||
    relativePath === 'styles/index.json' ||
    relativePath === 'icons/index.json' ||
    relativePath === 'validation-report.json' ||
    [
      'schema/registry.json',
      'schema/registry-index.json',
      'schema/registry-item.json',
      'schema/components.json',
    ].includes(relativePath)
  ) {
    return true
  }

  const match = /^styles\/([^/]+)\/([^/]+)\.json$/.exec(relativePath)
  return Boolean(
    match &&
    registryPathSegmentPattern.test(match[1]) &&
    (match[2] === 'index' || registryPathSegmentPattern.test(match[2])),
  )
}

function isManagedPreviewArtifactPath(relativePath: string) {
  return relativePath === 'index.tsx' || relativePath === 'icons.tsx'
}

async function pathContainsManagedSymlink(
  root: string,
  target: string,
  includeTarget: boolean,
) {
  const relativePath = path.relative(path.resolve(root), path.resolve(target))
  const segments = relativePath.split(path.sep).filter(Boolean)
  if (!includeTarget) segments.pop()

  let current = path.resolve(root)
  const candidates = [current]
  for (const segment of segments) {
    current = path.join(current, segment)
    candidates.push(current)
  }

  for (const candidate of candidates) {
    try {
      if ((await lstat(candidate)).isSymbolicLink()) return true
    } catch {
      // Missing paths will be created below the last verified real directory.
      return false
    }
  }
  return false
}

async function readPreviousManifest(
  outputDir: string,
): Promise<RegistryArtifactManifest> {
  try {
    const value = JSON.parse(
      await readFile(path.join(outputDir, '.registry-artifacts.json'), 'utf8'),
    ) as { files?: unknown; previewFiles?: unknown }
    return {
      found: true,
      files: Array.isArray(value.files)
        ? [
            ...new Set(
              value.files.flatMap((file) => {
                if (typeof file !== 'string') return []
                const normalized = normalizeManagedRelativePath(file)
                return normalized && isManagedPublicArtifactPath(normalized)
                  ? [normalized]
                  : []
              }),
            ),
          ]
        : [],
      previewFiles: Array.isArray(value.previewFiles)
        ? [
            ...new Set(
              value.previewFiles.flatMap((file) => {
                if (typeof file !== 'string') return []
                const normalized = normalizeManagedRelativePath(file)
                return normalized && isManagedPreviewArtifactPath(normalized)
                  ? [normalized]
                  : []
              }),
            ),
          ]
        : [],
    }
  } catch {
    return { found: false, files: [], previewFiles: [] }
  }
}

async function findFirstRunLegacyItemFiles(
  outputDir: string,
  currentPaths: ReadonlySet<string>,
) {
  const styleDirectories = new Set(
    [...currentPaths].flatMap((artifactPath) => {
      const match = /^styles\/([^/]+)\/index\.json$/.exec(artifactPath)
      return match ? [match[1]] : []
    }),
  )
  const stale: string[] = []

  for (const styleName of styleDirectories) {
    const relativeDirectory = `styles/${styleName}`
    const resolvedDirectory = resolveManagedPath(outputDir, relativeDirectory)
    if (!resolvedDirectory) continue

    try {
      const entries = await readdir(resolvedDirectory.path, {
        withFileTypes: true,
      })
      for (const entry of entries) {
        if (
          !entry.isFile() ||
          entry.name === 'index.json' ||
          !entry.name.endsWith('.json') ||
          !registryPathSegmentPattern.test(entry.name.slice(0, -'.json'.length))
        ) {
          continue
        }
        const relativePath = `${relativeDirectory}/${entry.name}`
        if (!currentPaths.has(relativePath)) stale.push(relativePath)
      }
    } catch {
      // The style directory does not exist on a clean first run.
    }
  }

  return stale
}

async function removeManagedFiles(root: string, relativePaths: string[]) {
  await settleFilesystemOperations(
    [...new Set(relativePaths)].map(async (relativePath) => {
      const resolved = resolveManagedPath(root, relativePath)
      if (
        resolved &&
        !(await pathContainsManagedSymlink(root, resolved.path, true))
      ) {
        await rm(resolved.path, { force: true })
      }
    }),
  )
}

async function settleFilesystemOperations(
  operations: Iterable<Promise<unknown>>,
) {
  const results = await Promise.allSettled(operations)
  const errors = results.flatMap((result) =>
    result.status === 'rejected' ? [result.reason] : [],
  )
  if (errors.length === 1) throw errors[0]
  if (errors.length > 1) {
    throw new AggregateError(
      errors,
      `Registry staging operations failed: ${errors
        .map((error) =>
          error instanceof Error ? error.message : String(error),
        )
        .join('; ')}`,
    )
  }
}

async function applyArtifactsToStaging(
  artifacts: RegistryArtifacts,
  outputDir: string,
  previewOutputDir: string,
) {
  const previousManifest = await readPreviousManifest(outputDir)
  const publicFiles = artifacts.files.filter(
    (artifact) => !artifact.path.startsWith('__registry__/'),
  )
  const previewFiles = artifacts.files.filter((artifact) =>
    artifact.path.startsWith('__registry__/'),
  )
  const currentPaths = new Set(publicFiles.map((artifact) => artifact.path))
  const currentPreviewPaths = new Set(
    previewFiles.map((artifact) => artifact.path.slice('__registry__/'.length)),
  )

  // Finish the complete new generation before deleting anything from the
  // previous one. A failed generation therefore cannot partially erase the
  // last known-good registry.
  await settleFilesystemOperations(
    publicFiles.map(async (artifact) => {
      const resolved = resolveManagedPath(outputDir, artifact.path)
      if (!resolved) {
        throw new TypeError(`Unsafe public artifact path: ${artifact.path}`)
      }
      if (await pathContainsManagedSymlink(outputDir, resolved.path, false)) {
        throw new TypeError(
          `Public artifact path resolves through a symbolic link: ${artifact.path}`,
        )
      }
      return writeAtomically(resolved.path, artifact.content)
    }),
  )

  await settleFilesystemOperations(
    previewFiles.map(async (artifact) => {
      const relativePath = artifact.path.slice('__registry__/'.length)
      const resolved = resolveManagedPath(previewOutputDir, relativePath)
      if (!resolved) {
        throw new TypeError(`Unsafe preview artifact path: ${artifact.path}`)
      }
      if (
        await pathContainsManagedSymlink(previewOutputDir, resolved.path, false)
      ) {
        throw new TypeError(
          `Preview artifact path resolves through a symbolic link: ${artifact.path}`,
        )
      }
      return writeAtomically(resolved.path, artifact.content)
    }),
  )

  const stalePublicFiles = previousManifest.files.filter(
    (previous) => !currentPaths.has(previous),
  )
  if (!previousManifest.found) {
    stalePublicFiles.push(
      ...(await findFirstRunLegacyItemFiles(outputDir, currentPaths)),
    )
  }
  await removeManagedFiles(outputDir, stalePublicFiles)
  await removeManagedFiles(
    previewOutputDir,
    previousManifest.previewFiles.filter(
      (previous) => !currentPreviewPaths.has(previous),
    ),
  )

  await writeAtomically(
    path.join(outputDir, '.registry-artifacts.json'),
    json({
      files: [...currentPaths].sort(compareText),
      previewFiles: [...currentPreviewPaths].sort(compareText),
    }),
  )
}

interface RegistryWriterLock {
  release: () => Promise<void>
}

interface RegistryWriterLockOwner {
  pid: number
  token: string
  updatedAt: number
}

interface PublicationTarget {
  root: string
  publicBase?: string
  previewBase?: string
  stage: string
  backup: string
  existed: boolean
  backedUp: boolean
  installed: boolean
}

const defaultLockTimeoutMs = 30_000
const defaultLockPollMs = 25
const defaultStaleLockMs = 5 * 60_000

function errorCode(error: unknown) {
  return error && typeof error === 'object' && 'code' in error
    ? Reflect.get(error, 'code')
    : undefined
}

function delay(milliseconds: number) {
  return new Promise<void>((resolve) => setTimeout(resolve, milliseconds))
}

function isProcessAlive(pid: number) {
  try {
    process.kill(pid, 0)
    return true
  } catch (error) {
    return errorCode(error) === 'EPERM'
  }
}

function registryLockPath(outputDir: string, previewOutputDir: string) {
  const outputRoot = path.resolve(outputDir)
  const previewRoot = path.resolve(previewOutputDir)
  const identity = sha256(`${outputRoot}\0${previewRoot}`).slice(0, 16)
  return path.join(
    path.dirname(outputRoot),
    `.${path.basename(outputRoot)}.registry-${identity}.lock`,
  )
}

async function lockIsStale(lockDir: string, staleLockMs: number) {
  try {
    const owner = JSON.parse(
      await readFile(path.join(lockDir, 'owner.json'), 'utf8'),
    ) as Partial<RegistryWriterLockOwner>
    const updatedAt =
      typeof owner.updatedAt === 'number' ? owner.updatedAt : Number.NaN
    const pid = typeof owner.pid === 'number' ? owner.pid : Number.NaN
    if (Number.isInteger(pid)) return !isProcessAlive(pid)
    return !Number.isFinite(updatedAt) || Date.now() - updatedAt > staleLockMs
  } catch {
    try {
      const metadata = await lstat(lockDir)
      return Date.now() - metadata.mtimeMs > staleLockMs
    } catch {
      return false
    }
  }
}

async function recoverStaleRegistryLock(lockDir: string, staleLockMs: number) {
  const recoveryLock = `${lockDir}.recovery`
  try {
    await mkdir(recoveryLock)
  } catch (error) {
    if (errorCode(error) !== 'EEXIST') throw error
    try {
      const metadata = await lstat(recoveryLock)
      if (Date.now() - metadata.mtimeMs > staleLockMs) {
        await rm(recoveryLock, { force: true, recursive: true })
      }
    } catch {
      // Another contender completed recovery between inspection and cleanup.
    }
    return false
  }

  try {
    if (!(await lockIsStale(lockDir, staleLockMs))) return false
    await rm(lockDir, { force: true, recursive: true })
    return true
  } finally {
    await rm(recoveryLock, { force: true, recursive: true })
  }
}

async function acquireRegistryWriterLock(
  outputDir: string,
  previewOutputDir: string,
  options: RegistryTransactionOptions,
): Promise<RegistryWriterLock> {
  const lockDir = registryLockPath(outputDir, previewOutputDir)
  const timeoutMs = options.lockTimeoutMs ?? defaultLockTimeoutMs
  const pollMs = Math.max(1, options.lockPollMs ?? defaultLockPollMs)
  const staleLockMs = Math.max(
    pollMs * 3,
    options.staleLockMs ?? defaultStaleLockMs,
  )
  const token = randomUUID()
  const startedAt = Date.now()
  const ownerPath = path.join(lockDir, 'owner.json')

  await mkdir(path.dirname(lockDir), { recursive: true })

  while (true) {
    try {
      await mkdir(lockDir)
      break
    } catch (error) {
      if (errorCode(error) !== 'EEXIST') throw error
      if (await recoverStaleRegistryLock(lockDir, staleLockMs)) {
        continue
      }
      if (Date.now() - startedAt >= timeoutMs) {
        throw new Error(
          `Timed out waiting for registry writer lock at ${lockDir}`,
        )
      }
      await delay(pollMs)
    }
  }

  const writeOwner = async () => {
    const owner: RegistryWriterLockOwner = {
      pid: process.pid,
      token,
      updatedAt: Date.now(),
    }
    await writeFile(ownerPath, JSON.stringify(owner), 'utf8')
  }

  try {
    await writeOwner()
  } catch (error) {
    await rm(lockDir, { force: true, recursive: true })
    throw error
  }

  return {
    release: async () => {
      try {
        const owner = JSON.parse(
          await readFile(ownerPath, 'utf8'),
        ) as Partial<RegistryWriterLockOwner>
        if (owner.token !== token) return
      } catch {
        return
      }
      await rm(lockDir, { force: true, recursive: true })
    },
  }
}

function relativeWithin(parent: string, child: string) {
  const relativePath = path.relative(path.resolve(parent), path.resolve(child))
  if (
    relativePath === '' ||
    (!path.isAbsolute(relativePath) &&
      relativePath !== '..' &&
      !relativePath.startsWith(`..${path.sep}`))
  ) {
    return relativePath
  }
  return undefined
}

function createPublicationTargets(
  outputDir: string,
  previewOutputDir: string,
  token: string,
) {
  const outputRoot = path.resolve(outputDir)
  const previewRoot = path.resolve(previewOutputDir)
  const previewWithinOutput = relativeWithin(outputRoot, previewRoot)
  const outputWithinPreview = relativeWithin(previewRoot, outputRoot)
  const target = (
    root: string,
    publicBase: string | undefined,
    previewBase: string | undefined,
  ): PublicationTarget => ({
    root,
    publicBase,
    previewBase,
    stage: `${root}.registry-stage-${token}`,
    backup: `${root}.registry-backup-${token}`,
    existed: false,
    backedUp: false,
    installed: false,
  })

  if (previewWithinOutput !== undefined) {
    return [target(outputRoot, '', previewWithinOutput)]
  }
  if (outputWithinPreview !== undefined) {
    return [target(previewRoot, outputWithinPreview, '')]
  }
  return [target(outputRoot, '', undefined), target(previewRoot, undefined, '')]
}

async function stagePublicationTarget(target: PublicationTarget) {
  await mkdir(path.dirname(target.root), { recursive: true })
  try {
    const metadata = await lstat(target.root)
    if (metadata.isSymbolicLink()) {
      throw new TypeError(
        `Registry publication root must not be a symbolic link: ${target.root}`,
      )
    }
    if (!metadata.isDirectory()) {
      throw new TypeError(
        `Registry publication root must be a directory: ${target.root}`,
      )
    }
    target.existed = true
  } catch (error) {
    if (errorCode(error) !== 'ENOENT') throw error
  }

  if (target.existed) {
    await cp(target.root, target.stage, {
      recursive: true,
      dereference: false,
      errorOnExist: true,
      force: false,
    })
  } else {
    await mkdir(target.stage)
  }
}

async function rollbackPublicationTargets(targets: PublicationTarget[]) {
  const rollbackErrors: unknown[] = []

  for (const target of [...targets].reverse()) {
    const discarded = `${target.stage}.discarded`
    try {
      if (target.installed) {
        await rename(target.root, discarded)
        target.installed = false
      }
      if (target.backedUp) {
        await rename(target.backup, target.root)
        target.backedUp = false
      }
      await rm(discarded, { force: true, recursive: true })
    } catch (error) {
      rollbackErrors.push(error)
    }
  }

  if (rollbackErrors.length) {
    throw new AggregateError(
      rollbackErrors,
      'Registry publication rollback failed',
    )
  }
}

async function commitPublicationTarget(target: PublicationTarget) {
  if (target.existed) {
    await rename(target.root, target.backup)
    target.backedUp = true
  }

  try {
    await rename(target.stage, target.root)
    target.installed = true
  } catch (error) {
    if (target.backedUp) {
      await rename(target.backup, target.root)
      target.backedUp = false
    }
    throw error
  }
}

async function cleanupPublicationTargets(targets: PublicationTarget[]) {
  await Promise.allSettled(
    targets.flatMap((target) => [
      rm(target.stage, { force: true, recursive: true }),
      rm(target.backup, { force: true, recursive: true }),
      rm(`${target.stage}.discarded`, { force: true, recursive: true }),
    ]),
  )
}

/**
 * Publish an already-built artifact set.
 *
 * Concurrent writers for the same public/preview pair are serialized and each
 * publication root is committed as a complete directory, so no committed root
 * contains a file-by-file mixture. Node does not expose an atomic exchange for
 * two non-empty directories, so a reader can briefly observe a root as absent
 * between its backup and install renames. When both outputs share a root, one
 * directory transaction publishes them together. For disjoint roots (which
 * may be on different filesystems), they are committed in order under the same
 * lock and any failure rolls earlier roots back before the lock is released.
 */
export async function publishRegistryArtifacts(
  artifacts: RegistryArtifacts,
  options: EmitRegistryOptions,
) {
  if (!options.outputDir) return artifacts

  const outputDir = path.resolve(options.outputDir)
  const previewOutputDir = path.resolve(
    options.previewOutputDir ?? path.join(outputDir, '__registry__'),
  )
  const transaction = options.transaction ?? {}
  const phase = async (value: RegistryTransactionPhase) =>
    transaction.onPhase?.(value)
  const writerLock = await acquireRegistryWriterLock(
    outputDir,
    previewOutputDir,
    transaction,
  )
  const targets = createPublicationTargets(
    outputDir,
    previewOutputDir,
    randomUUID(),
  )
  let preserveRecoveryState = false

  try {
    await phase('locked')
    for (const target of targets) {
      await stagePublicationTarget(target)
    }

    const publicTarget = targets.find(
      (target) => target.publicBase !== undefined,
    )
    const previewTarget = targets.find(
      (target) => target.previewBase !== undefined,
    )
    if (!publicTarget || !previewTarget) {
      throw new Error('Registry publication targets are incomplete')
    }
    await applyArtifactsToStaging(
      artifacts,
      path.join(publicTarget.stage, publicTarget.publicBase ?? ''),
      path.join(previewTarget.stage, previewTarget.previewBase ?? ''),
    )
    await phase('staged')
    await phase('before-commit')

    try {
      for (const target of targets) {
        await commitPublicationTarget(target)
        if (target.publicBase !== undefined) {
          await phase('public-committed')
        }
        if (target.previewBase !== undefined) {
          await phase('preview-committed')
        }
      }
      await phase('committed')
    } catch (error) {
      let rollbackError: unknown
      try {
        await rollbackPublicationTargets(targets)
        await phase('rollback')
      } catch (caught) {
        rollbackError = caught
      }
      if (rollbackError) {
        preserveRecoveryState = true
        throw new AggregateError(
          [error, rollbackError],
          'Registry publication and rollback failed',
        )
      }
      throw error
    }

    return artifacts
  } finally {
    if (!preserveRecoveryState) {
      await cleanupPublicationTargets(targets)
    }
    await writerLock.release()
  }
}

/**
 * Emit deterministic artifacts and optionally write them to disk. Generation
 * is deliberately network-free: icon payloads must already be present in the
 * compiled in-memory model as checked-in TSX source.
 */
export async function emitRegistryArtifacts(
  input: EmitRegistryInput,
  options: EmitRegistryOptions = {},
) {
  const artifacts = createRegistryArtifacts(input, options)
  return publishRegistryArtifacts(artifacts, options)
}
