// @ts-nocheck
// This file is autogenerated by scripts/build-registry.ts
// Do not edit this file directly.
import * as React from "react"

export const Icons = {
  "ArrowLeft": {
  lucide: React.lazy(() => import("lucide-react").then(mod => ({
    default: mod.ArrowLeft
  }))),
  tabler: React.lazy(() => import("@tabler/icons-react").then(mod => ({
    default: mod.IconArrowLeft
  }))),
},  "Calendar": {
  lucide: React.lazy(() => import("lucide-react").then(mod => ({
    default: mod.Calendar
  }))),
  tabler: React.lazy(() => import("@tabler/icons-react").then(mod => ({
    default: mod.IconCalendar
  }))),
},  "Check": {
  lucide: React.lazy(() => import("lucide-react").then(mod => ({
    default: mod.Check
  }))),
  tabler: React.lazy(() => import("@tabler/icons-react").then(mod => ({
    default: mod.IconCheck
  }))),
},  "ChevronDown": {
  lucide: React.lazy(() => import("lucide-react").then(mod => ({
    default: mod.ChevronDown
  }))),
  tabler: React.lazy(() => import("@tabler/icons-react").then(mod => ({
    default: mod.IconChevronDown
  }))),
},  "ChevronLeft": {
  lucide: React.lazy(() => import("lucide-react").then(mod => ({
    default: mod.ChevronLeft
  }))),
  tabler: React.lazy(() => import("@tabler/icons-react").then(mod => ({
    default: mod.IconChevronLeft
  }))),
},  "ChevronRight": {
  lucide: React.lazy(() => import("lucide-react").then(mod => ({
    default: mod.ChevronRight
  }))),
  tabler: React.lazy(() => import("@tabler/icons-react").then(mod => ({
    default: mod.IconChevronRight
  }))),
},  "ChevronUp": {
  lucide: React.lazy(() => import("lucide-react").then(mod => ({
    default: mod.ChevronUp
  }))),
  tabler: React.lazy(() => import("@tabler/icons-react").then(mod => ({
    default: mod.IconChevronUp
  }))),
},  "Close": {
  lucide: React.lazy(() => import("lucide-react").then(mod => ({
    default: mod.X
  }))),
  tabler: React.lazy(() => import("@tabler/icons-react").then(mod => ({
    default: mod.IconX
  }))),
},  "Copy": {
  lucide: React.lazy(() => import("lucide-react").then(mod => ({
    default: mod.Copy
  }))),
  tabler: React.lazy(() => import("@tabler/icons-react").then(mod => ({
    default: mod.IconCopy
  }))),
},  "Ellipsis": {
  lucide: React.lazy(() => import("lucide-react").then(mod => ({
    default: mod.MoreHorizontal
  }))),
  tabler: React.lazy(() => import("@tabler/icons-react").then(mod => ({
    default: mod.IconDots
  }))),
},  "Eye": {
  lucide: React.lazy(() => import("lucide-react").then(mod => ({
    default: mod.Eye
  }))),
  tabler: React.lazy(() => import("@tabler/icons-react").then(mod => ({
    default: mod.IconEye
  }))),
},  "EyeOff": {
  lucide: React.lazy(() => import("lucide-react").then(mod => ({
    default: mod.EyeOff
  }))),
  tabler: React.lazy(() => import("@tabler/icons-react").then(mod => ({
    default: mod.IconEyeOff
  }))),
},  "Filter": {
  lucide: React.lazy(() => import("lucide-react").then(mod => ({
    default: mod.Filter
  }))),
  tabler: React.lazy(() => import("@tabler/icons-react").then(mod => ({
    default: mod.IconFilter
  }))),
},  "Hamburger": {
  lucide: React.lazy(() => import("lucide-react").then(mod => ({
    default: mod.Menu
  }))),
  tabler: React.lazy(() => import("@tabler/icons-react").then(mod => ({
    default: mod.IconMenu2
  }))),
},  "Info": {
  lucide: React.lazy(() => import("lucide-react").then(mod => ({
    default: mod.Info
  }))),
  tabler: React.lazy(() => import("@tabler/icons-react").then(mod => ({
    default: mod.IconInfoCircle
  }))),
},  "Minus": {
  lucide: React.lazy(() => import("lucide-react").then(mod => ({
    default: mod.Minus
  }))),
  tabler: React.lazy(() => import("@tabler/icons-react").then(mod => ({
    default: mod.IconMinus
  }))),
},  "Plus": {
  lucide: React.lazy(() => import("lucide-react").then(mod => ({
    default: mod.Plus
  }))),
  tabler: React.lazy(() => import("@tabler/icons-react").then(mod => ({
    default: mod.IconPlus
  }))),
},  "Search": {
  lucide: React.lazy(() => import("lucide-react").then(mod => ({
    default: mod.Search
  }))),
  tabler: React.lazy(() => import("@tabler/icons-react").then(mod => ({
    default: mod.IconSearch
  }))),
},  "ViewOff": {
  lucide: React.lazy(() => import("lucide-react").then(mod => ({
    default: mod.EyeOff
  }))),
  tabler: React.lazy(() => import("@tabler/icons-react").then(mod => ({
    default: mod.IconEyeOff
  }))),
},  "View": {
  lucide: React.lazy(() => import("lucide-react").then(mod => ({
    default: mod.Eye
  }))),
  tabler: React.lazy(() => import("@tabler/icons-react").then(mod => ({
    default: mod.IconEye
  }))),
},
}
