// @ts-nocheck
// This file is generated by @saas-ui/registry/compiler.
// Do not edit this file directly.
import * as React from 'react'

export const Icons = {
  "ArrowLeft": {
    "lucide": React.lazy(() => import("lucide-react").then((module) => ({ default: module["ArrowLeft"] }))),
    "tabler": React.lazy(() => import("@tabler/icons-react").then((module) => ({ default: module["IconArrowLeft"] }))),
  },
  "Calendar": {
    "lucide": React.lazy(() => import("lucide-react").then((module) => ({ default: module["Calendar"] }))),
    "tabler": React.lazy(() => import("@tabler/icons-react").then((module) => ({ default: module["IconCalendar"] }))),
  },
  "Check": {
    "lucide": React.lazy(() => import("lucide-react").then((module) => ({ default: module["Check"] }))),
    "tabler": React.lazy(() => import("@tabler/icons-react").then((module) => ({ default: module["IconCheck"] }))),
  },
  "ChevronDown": {
    "lucide": React.lazy(() => import("lucide-react").then((module) => ({ default: module["ChevronDown"] }))),
    "tabler": React.lazy(() => import("@tabler/icons-react").then((module) => ({ default: module["IconChevronDown"] }))),
  },
  "ChevronLeft": {
    "lucide": React.lazy(() => import("lucide-react").then((module) => ({ default: module["ChevronLeft"] }))),
    "tabler": React.lazy(() => import("@tabler/icons-react").then((module) => ({ default: module["IconChevronLeft"] }))),
  },
  "ChevronRight": {
    "lucide": React.lazy(() => import("lucide-react").then((module) => ({ default: module["ChevronRight"] }))),
    "tabler": React.lazy(() => import("@tabler/icons-react").then((module) => ({ default: module["IconChevronRight"] }))),
  },
  "ChevronUp": {
    "lucide": React.lazy(() => import("lucide-react").then((module) => ({ default: module["ChevronUp"] }))),
    "tabler": React.lazy(() => import("@tabler/icons-react").then((module) => ({ default: module["IconChevronUp"] }))),
  },
  "Close": {
    "lucide": React.lazy(() => import("lucide-react").then((module) => ({ default: module["X"] }))),
    "tabler": React.lazy(() => import("@tabler/icons-react").then((module) => ({ default: module["IconX"] }))),
  },
  "Copy": {
    "lucide": React.lazy(() => import("lucide-react").then((module) => ({ default: module["Copy"] }))),
    "tabler": React.lazy(() => import("@tabler/icons-react").then((module) => ({ default: module["IconCopy"] }))),
  },
  "Ellipsis": {
    "lucide": React.lazy(() => import("lucide-react").then((module) => ({ default: module["Ellipsis"] }))),
    "tabler": React.lazy(() => import("@tabler/icons-react").then((module) => ({ default: module["IconDots"] }))),
  },
  "Eye": {
    "lucide": React.lazy(() => import("lucide-react").then((module) => ({ default: module["Eye"] }))),
    "tabler": React.lazy(() => import("@tabler/icons-react").then((module) => ({ default: module["IconEye"] }))),
  },
  "EyeOff": {
    "lucide": React.lazy(() => import("lucide-react").then((module) => ({ default: module["EyeOff"] }))),
    "tabler": React.lazy(() => import("@tabler/icons-react").then((module) => ({ default: module["IconEyeOff"] }))),
  },
  "Filter": {
    "lucide": React.lazy(() => import("lucide-react").then((module) => ({ default: module["Filter"] }))),
    "tabler": React.lazy(() => import("@tabler/icons-react").then((module) => ({ default: module["IconFilter"] }))),
  },
  "Hamburger": {
    "lucide": React.lazy(() => import("lucide-react").then((module) => ({ default: module["Menu"] }))),
    "tabler": React.lazy(() => import("@tabler/icons-react").then((module) => ({ default: module["IconMenu2"] }))),
  },
  "Info": {
    "lucide": React.lazy(() => import("lucide-react").then((module) => ({ default: module["Info"] }))),
    "tabler": React.lazy(() => import("@tabler/icons-react").then((module) => ({ default: module["IconInfoCircle"] }))),
  },
  "Minus": {
    "lucide": React.lazy(() => import("lucide-react").then((module) => ({ default: module["Minus"] }))),
    "tabler": React.lazy(() => import("@tabler/icons-react").then((module) => ({ default: module["IconMinus"] }))),
  },
  "Plus": {
    "lucide": React.lazy(() => import("lucide-react").then((module) => ({ default: module["Plus"] }))),
    "tabler": React.lazy(() => import("@tabler/icons-react").then((module) => ({ default: module["IconPlus"] }))),
  },
  "Search": {
    "lucide": React.lazy(() => import("lucide-react").then((module) => ({ default: module["Search"] }))),
    "tabler": React.lazy(() => import("@tabler/icons-react").then((module) => ({ default: module["IconSearch"] }))),
  },
  "View": {
    "lucide": React.lazy(() => import("lucide-react").then((module) => ({ default: module["Eye"] }))),
    "tabler": React.lazy(() => import("@tabler/icons-react").then((module) => ({ default: module["IconEye"] }))),
  },
  "ViewOff": {
    "lucide": React.lazy(() => import("lucide-react").then((module) => ({ default: module["EyeOff"] }))),
    "tabler": React.lazy(() => import("@tabler/icons-react").then((module) => ({ default: module["IconEyeOff"] }))),
  },
}
