// @ts-nocheck
// This file is autogenerated by scripts/build-registry.ts
// Do not edit this file directly.
import * as React from "react"

export const Index: Record<string, any> = {
  "default": {
    "accordion": {
      name: "accordion",
      type: "registry:ui",
      registryDependencies: ["icons"],
      files: ["../ui/accordion/accordion.tsx","../ui/accordion/index.ts"],
      component: React.lazy(() => import("@/registry/default/ui/accordion/accordion.tsx")),
      source: "",
      categories: undefined,
      chunks: []
    },
    "action-bar": {
      name: "action-bar",
      type: "registry:ui",
      registryDependencies: ["close-button"],
      files: ["../ui/action-bar/action-bar.tsx","../ui/action-bar/index.ts"],
      component: React.lazy(() => import("@/registry/default/ui/action-bar/action-bar.tsx")),
      source: "",
      categories: undefined,
      chunks: []
    },
    "alert": {
      name: "alert",
      type: "registry:ui",
      registryDependencies: ["close-button"],
      files: ["../ui/alert/alert.tsx","../ui/alert/index.ts"],
      component: React.lazy(() => import("@/registry/default/ui/alert/alert.tsx")),
      source: "",
      categories: undefined,
      chunks: []
    },
    "app-shell": {
      name: "app-shell",
      type: "registry:ui",
      registryDependencies: [],
      files: ["../ui/app-shell/app-shell.tsx","../ui/app-shell/index.ts"],
      component: React.lazy(() => import("@/registry/default/ui/app-shell/app-shell.tsx")),
      source: "",
      categories: undefined,
      chunks: []
    },
    "avatar": {
      name: "avatar",
      type: "registry:ui",
      registryDependencies: [],
      files: ["../ui/avatar/avatar.tsx","../ui/avatar/index.ts"],
      component: React.lazy(() => import("@/registry/default/ui/avatar/avatar.tsx")),
      source: "",
      categories: undefined,
      chunks: []
    },
    "back-button": {
      name: "back-button",
      type: "registry:ui",
      registryDependencies: ["icons","link"],
      files: ["../ui/back-button/back-button.tsx","../ui/back-button/index.ts"],
      component: React.lazy(() => import("@/registry/default/ui/back-button/back-button.tsx")),
      source: "",
      categories: undefined,
      chunks: []
    },
    "blockquote": {
      name: "blockquote",
      type: "registry:ui",
      registryDependencies: [],
      files: ["../ui/blockquote/blockquote.tsx","../ui/blockquote/index.ts"],
      component: React.lazy(() => import("@/registry/default/ui/blockquote/blockquote.tsx")),
      source: "",
      categories: undefined,
      chunks: []
    },
    "breadcrumb": {
      name: "breadcrumb",
      type: "registry:ui",
      registryDependencies: [],
      files: ["../ui/breadcrumb/breadcrumb.tsx","../ui/breadcrumb/index.ts"],
      component: React.lazy(() => import("@/registry/default/ui/breadcrumb/breadcrumb.tsx")),
      source: "",
      categories: undefined,
      chunks: []
    },
    "checkbox": {
      name: "checkbox",
      type: "registry:ui",
      registryDependencies: [],
      files: ["../ui/checkbox/checkbox.tsx","../ui/checkbox/index.ts"],
      component: React.lazy(() => import("@/registry/default/ui/checkbox/checkbox.tsx")),
      source: "",
      categories: undefined,
      chunks: []
    },
    "checkbox-card": {
      name: "checkbox-card",
      type: "registry:ui",
      registryDependencies: [],
      files: ["../ui/checkbox-card/checkbox-card.tsx","../ui/checkbox-card/index.ts"],
      component: React.lazy(() => import("@/registry/default/ui/checkbox-card/checkbox-card.tsx")),
      source: "",
      categories: undefined,
      chunks: []
    },
    "clipboard": {
      name: "clipboard",
      type: "registry:ui",
      registryDependencies: ["button","icon-button","icons","input"],
      files: ["../ui/clipboard/clipboard.tsx","../ui/clipboard/index.ts"],
      component: React.lazy(() => import("@/registry/default/ui/clipboard/clipboard.tsx")),
      source: "",
      categories: undefined,
      chunks: []
    },
    "close-button": {
      name: "close-button",
      type: "registry:ui",
      registryDependencies: ["icons"],
      files: ["../ui/close-button/close-button.tsx","../ui/close-button/index.ts"],
      component: React.lazy(() => import("@/registry/default/ui/close-button/close-button.tsx")),
      source: "",
      categories: undefined,
      chunks: []
    },
    "color-mode": {
      name: "color-mode",
      type: "registry:ui",
      registryDependencies: [],
      files: ["../ui/color-mode/color-mode.tsx","../ui/color-mode/index.ts"],
      component: React.lazy(() => import("@/registry/default/ui/color-mode/color-mode.tsx")),
      source: "",
      categories: undefined,
      chunks: []
    },
    "command": {
      name: "command",
      type: "registry:ui",
      registryDependencies: [],
      files: ["../ui/command/command.tsx","../ui/command/index.ts"],
      component: React.lazy(() => import("@/registry/default/ui/command/command.tsx")),
      source: "",
      categories: undefined,
      chunks: []
    },
    "dialog": {
      name: "dialog",
      type: "registry:ui",
      registryDependencies: ["close-button"],
      files: ["../ui/dialog/dialog.tsx","../ui/dialog/index.ts"],
      component: React.lazy(() => import("@/registry/default/ui/dialog/dialog.tsx")),
      source: "",
      categories: undefined,
      chunks: []
    },
    "drawer": {
      name: "drawer",
      type: "registry:ui",
      registryDependencies: ["close-button"],
      files: ["../ui/drawer/drawer.tsx","../ui/drawer/index.ts"],
      component: React.lazy(() => import("@/registry/default/ui/drawer/drawer.tsx")),
      source: "",
      categories: undefined,
      chunks: []
    },
    "empty-state": {
      name: "empty-state",
      type: "registry:ui",
      registryDependencies: [],
      files: ["../ui/empty-state/empty-state.tsx","../ui/empty-state/index.ts"],
      component: React.lazy(() => import("@/registry/default/ui/empty-state/empty-state.tsx")),
      source: "",
      categories: undefined,
      chunks: []
    },
    "file-upload": {
      name: "file-upload",
      type: "registry:ui",
      registryDependencies: ["button","close-button"],
      files: ["../ui/file-upload/file-upload.tsx","../ui/file-upload/index.ts"],
      component: React.lazy(() => import("@/registry/default/ui/file-upload/file-upload.tsx")),
      source: "",
      categories: undefined,
      chunks: []
    },
    "grid-list": {
      name: "grid-list",
      type: "registry:ui",
      registryDependencies: ["./grid-list.context.ts"],
      files: ["../ui/grid-list/grid-list.tsx","../ui/grid-list/index.ts"],
      component: React.lazy(() => import("@/registry/default/ui/grid-list/grid-list.tsx")),
      source: "",
      categories: undefined,
      chunks: []
    },
    "hover-card": {
      name: "hover-card",
      type: "registry:ui",
      registryDependencies: [],
      files: ["../ui/hover-card/hover-card.tsx","../ui/hover-card/index.ts"],
      component: React.lazy(() => import("@/registry/default/ui/hover-card/hover-card.tsx")),
      source: "",
      categories: undefined,
      chunks: []
    },
    "icon-badge": {
      name: "icon-badge",
      type: "registry:ui",
      registryDependencies: [],
      files: ["../ui/icon-badge/icon-badge.tsx","../ui/icon-badge/index.ts"],
      component: React.lazy(() => import("@/registry/default/ui/icon-badge/icon-badge.tsx")),
      source: "",
      categories: undefined,
      chunks: []
    },
    "icons": {
      name: "icons",
      type: "registry:ui",
      registryDependencies: ["./create-icon.tsx"],
      files: ["../ui/icons/icons.tsx","../ui/icons/index.ts"],
      component: React.lazy(() => import("@/registry/default/ui/icons/icons.tsx")),
      source: "",
      categories: undefined,
      chunks: []
    },
    "info-tip": {
      name: "info-tip",
      type: "registry:ui",
      registryDependencies: ["icon-button","icons","toggle-tip"],
      files: ["../ui/info-tip/info-tip.tsx","../ui/info-tip/index.ts"],
      component: React.lazy(() => import("@/registry/default/ui/info-tip/info-tip.tsx")),
      source: "",
      categories: undefined,
      chunks: []
    },
    "loading-overlay": {
      name: "loading-overlay",
      type: "registry:ui",
      registryDependencies: ["spinner","./loading-overlay.context.ts"],
      files: ["../ui/loading-overlay/loading-overlay.tsx","../ui/loading-overlay/index.ts"],
      component: React.lazy(() => import("@/registry/default/ui/loading-overlay/loading-overlay.tsx")),
      source: "",
      categories: undefined,
      chunks: []
    },
    "menu": {
      name: "menu",
      type: "registry:ui",
      registryDependencies: ["button","icons"],
      files: ["../ui/menu/menu.tsx","../ui/menu/index.ts"],
      component: React.lazy(() => import("@/registry/default/ui/menu/menu.tsx")),
      source: "",
      categories: undefined,
      chunks: []
    },
    "native-select": {
      name: "native-select",
      type: "registry:ui",
      registryDependencies: ["icons"],
      files: ["../ui/native-select/native-select.tsx","../ui/native-select/index.ts"],
      component: React.lazy(() => import("@/registry/default/ui/native-select/native-select.tsx")),
      source: "",
      categories: undefined,
      chunks: []
    },
    "navbar": {
      name: "navbar",
      type: "registry:ui",
      registryDependencies: ["../provider/use-link.tsx","./navbar.context.ts"],
      files: ["../ui/navbar/navbar.tsx","../ui/navbar/index.ts"],
      component: React.lazy(() => import("@/registry/default/ui/navbar/navbar.tsx")),
      source: "",
      categories: undefined,
      chunks: []
    },
    "number-input": {
      name: "number-input",
      type: "registry:ui",
      registryDependencies: ["input-group"],
      files: ["../ui/number-input/number-input.tsx","../ui/number-input/index.ts"],
      component: React.lazy(() => import("@/registry/default/ui/number-input/number-input.tsx")),
      source: "",
      categories: undefined,
      chunks: []
    },
    "page": {
      name: "page",
      type: "registry:ui",
      registryDependencies: ["loading-overlay","./page.context.ts"],
      files: ["../ui/page/page.tsx","../ui/page/index.ts"],
      component: React.lazy(() => import("@/registry/default/ui/page/page.tsx")),
      source: "",
      categories: undefined,
      chunks: []
    },
    "pagination": {
      name: "pagination",
      type: "registry:ui",
      registryDependencies: ["icons"],
      files: ["../ui/pagination/pagination.tsx","../ui/pagination/index.ts"],
      component: React.lazy(() => import("@/registry/default/ui/pagination/pagination.tsx")),
      source: "",
      categories: undefined,
      chunks: []
    },
    "password-input": {
      name: "password-input",
      type: "registry:ui",
      registryDependencies: ["icons"],
      files: ["../ui/password-input/password-input.tsx","../ui/password-input/index.ts"],
      component: React.lazy(() => import("@/registry/default/ui/password-input/password-input.tsx")),
      source: "",
      categories: undefined,
      chunks: []
    },
    "persona": {
      name: "persona",
      type: "registry:ui",
      registryDependencies: ["avatar/avatar.tsx","./persona.context.ts","./presence.ts"],
      files: ["../ui/persona/persona.tsx","../ui/persona/index.ts"],
      component: React.lazy(() => import("@/registry/default/ui/persona/persona.tsx")),
      source: "",
      categories: undefined,
      chunks: []
    },
    "pin-input": {
      name: "pin-input",
      type: "registry:ui",
      registryDependencies: [],
      files: ["../ui/pin-input/pin-input.tsx","../ui/pin-input/index.ts"],
      component: React.lazy(() => import("@/registry/default/ui/pin-input/pin-input.tsx")),
      source: "",
      categories: undefined,
      chunks: []
    },
    "popover": {
      name: "popover",
      type: "registry:ui",
      registryDependencies: ["close-button"],
      files: ["../ui/popover/popover.tsx","../ui/popover/index.ts"],
      component: React.lazy(() => import("@/registry/default/ui/popover/popover.tsx")),
      source: "",
      categories: undefined,
      chunks: []
    },
    "radio": {
      name: "radio",
      type: "registry:ui",
      registryDependencies: [],
      files: ["../ui/radio/radio.tsx","../ui/radio/index.ts"],
      component: React.lazy(() => import("@/registry/default/ui/radio/radio.tsx")),
      source: "",
      categories: undefined,
      chunks: []
    },
    "radio-card": {
      name: "radio-card",
      type: "registry:ui",
      registryDependencies: [],
      files: ["../ui/radio-card/radio-card.tsx","../ui/radio-card/index.ts"],
      component: React.lazy(() => import("@/registry/default/ui/radio-card/radio-card.tsx")),
      source: "",
      categories: undefined,
      chunks: []
    },
    "search-input": {
      name: "search-input",
      type: "registry:ui",
      registryDependencies: ["icons"],
      files: ["../ui/search-input/search-input.tsx","../ui/search-input/index.ts"],
      component: React.lazy(() => import("@/registry/default/ui/search-input/search-input.tsx")),
      source: "",
      categories: undefined,
      chunks: []
    },
    "section": {
      name: "section",
      type: "registry:ui",
      registryDependencies: ["./section.context.ts"],
      files: ["../ui/section/section.tsx","../ui/section/index.ts"],
      component: React.lazy(() => import("@/registry/default/ui/section/section.tsx")),
      source: "",
      categories: undefined,
      chunks: []
    },
    "segmented-control": {
      name: "segmented-control",
      type: "registry:ui",
      registryDependencies: [],
      files: ["../ui/segmented-control/segmented-control.tsx","../ui/segmented-control/index.ts"],
      component: React.lazy(() => import("@/registry/default/ui/segmented-control/segmented-control.tsx")),
      source: "",
      categories: undefined,
      chunks: []
    },
    "select": {
      name: "select",
      type: "registry:ui",
      registryDependencies: ["close-button"],
      files: ["../ui/select/select.tsx","../ui/select/index.ts"],
      component: React.lazy(() => import("@/registry/default/ui/select/select.tsx")),
      source: "",
      categories: undefined,
      chunks: []
    },
    "sidebar": {
      name: "sidebar",
      type: "registry:ui",
      registryDependencies: ["./sidebar.context.ts"],
      files: ["../ui/sidebar/sidebar.tsx","../ui/sidebar/index.ts"],
      component: React.lazy(() => import("@/registry/default/ui/sidebar/sidebar.tsx")),
      source: "",
      categories: undefined,
      chunks: []
    },
    "skeleton": {
      name: "skeleton",
      type: "registry:ui",
      registryDependencies: [],
      files: ["../ui/skeleton/skeleton.tsx","../ui/skeleton/index.ts"],
      component: React.lazy(() => import("@/registry/default/ui/skeleton/skeleton.tsx")),
      source: "",
      categories: undefined,
      chunks: []
    },
    "slider": {
      name: "slider",
      type: "registry:ui",
      registryDependencies: [],
      files: ["../ui/slider/slider.tsx","../ui/slider/index.ts"],
      component: React.lazy(() => import("@/registry/default/ui/slider/slider.tsx")),
      source: "",
      categories: undefined,
      chunks: []
    },
    "spinner": {
      name: "spinner",
      type: "registry:ui",
      registryDependencies: [],
      files: ["../ui/spinner/spinner.tsx","../ui/spinner/index.ts"],
      component: React.lazy(() => import("@/registry/default/ui/spinner/spinner.tsx")),
      source: "",
      categories: undefined,
      chunks: []
    },
    "stat": {
      name: "stat",
      type: "registry:ui",
      registryDependencies: [],
      files: ["../ui/stat/stat.tsx","../ui/stat/index.ts"],
      component: React.lazy(() => import("@/registry/default/ui/stat/stat.tsx")),
      source: "",
      categories: undefined,
      chunks: []
    },
    "status": {
      name: "status",
      type: "registry:ui",
      registryDependencies: [],
      files: ["../ui/status/status.tsx","../ui/status/index.ts"],
      component: React.lazy(() => import("@/registry/default/ui/status/status.tsx")),
      source: "",
      categories: undefined,
      chunks: []
    },
    "steps": {
      name: "steps",
      type: "registry:ui",
      registryDependencies: ["icons"],
      files: ["../ui/steps/steps.tsx","../ui/steps/index.ts"],
      component: React.lazy(() => import("@/registry/default/ui/steps/steps.tsx")),
      source: "",
      categories: undefined,
      chunks: []
    },
    "switch": {
      name: "switch",
      type: "registry:ui",
      registryDependencies: [],
      files: ["../ui/switch/switch.tsx","../ui/switch/index.ts"],
      component: React.lazy(() => import("@/registry/default/ui/switch/switch.tsx")),
      source: "",
      categories: undefined,
      chunks: []
    },
    "tag": {
      name: "tag",
      type: "registry:ui",
      registryDependencies: [],
      files: ["../ui/tag/tag.tsx","../ui/tag/index.ts"],
      component: React.lazy(() => import("@/registry/default/ui/tag/tag.tsx")),
      source: "",
      categories: undefined,
      chunks: []
    },
    "toaster": {
      name: "toaster",
      type: "registry:ui",
      registryDependencies: ["close-button","spinner"],
      files: ["../ui/toaster/toaster.tsx","../ui/toaster/index.ts"],
      component: React.lazy(() => import("@/registry/default/ui/toaster/toaster.tsx")),
      source: "",
      categories: undefined,
      chunks: []
    },
    "toggle-tip": {
      name: "toggle-tip",
      type: "registry:ui",
      registryDependencies: ["popover","portal"],
      files: ["../ui/toggle-tip/toggle-tip.tsx","../ui/toggle-tip/index.ts"],
      component: React.lazy(() => import("@/registry/default/ui/toggle-tip/toggle-tip.tsx")),
      source: "",
      categories: undefined,
      chunks: []
    },
    "tooltip": {
      name: "tooltip",
      type: "registry:ui",
      registryDependencies: [],
      files: ["../ui/tooltip/tooltip.tsx","../ui/tooltip/index.ts"],
      component: React.lazy(() => import("@/registry/default/ui/tooltip/tooltip.tsx")),
      source: "",
      categories: undefined,
      chunks: []
    },
  },
}
